// Code generated by ent, DO NOT EDIT.

package resellerdomain

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the resellerdomain type in the database.
	Label = "reseller_domain"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldSiteName holds the string denoting the site_name field in the database.
	FieldSiteName = "site_name"
	// FieldSiteLogo holds the string denoting the site_logo field in the database.
	FieldSiteLogo = "site_logo"
	// FieldSiteSubtitle holds the string denoting the site_subtitle field in the database.
	FieldSiteSubtitle = "site_subtitle"
	// Table holds the table name of the resellerdomain in the database.
	Table = "reseller_domains"
)

// Columns holds all SQL columns for resellerdomain fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDomain,
	FieldUserID,
	FieldStatus,
	FieldNotes,
	FieldSiteName,
	FieldSiteLogo,
	FieldSiteSubtitle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	DomainValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultSiteName holds the default value on creation for the "site_name" field.
	DefaultSiteName string
	// SiteNameValidator is a validator for the "site_name" field. It is called by the builders before save.
	SiteNameValidator func(string) error
	// DefaultSiteLogo holds the default value on creation for the "site_logo" field.
	DefaultSiteLogo string
	// DefaultSiteSubtitle holds the default value on creation for the "site_subtitle" field.
	DefaultSiteSubtitle string
	// SiteSubtitleValidator is a validator for the "site_subtitle" field. It is called by the builders before save.
	SiteSubtitleValidator func(string) error
)

// OrderOption defines the ordering options for the ResellerDomain queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// BySiteName orders the results by the site_name field.
func BySiteName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteName, opts...).ToFunc()
}

// BySiteLogo orders the results by the site_logo field.
func BySiteLogo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteLogo, opts...).ToFunc()
}

// BySiteSubtitle orders the results by the site_subtitle field.
func BySiteSubtitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteSubtitle, opts...).ToFunc()
}
