// Code generated by ent, DO NOT EDIT.

package resellerdomain

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldUpdatedAt, v))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldDomain, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldUserID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldStatus, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldNotes, v))
}

// SiteName applies equality check predicate on the "site_name" field. It's identical to SiteNameEQ.
func SiteName(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldSiteName, v))
}

// SiteLogo applies equality check predicate on the "site_logo" field. It's identical to SiteLogoEQ.
func SiteLogo(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldSiteLogo, v))
}

// SiteSubtitle applies equality check predicate on the "site_subtitle" field. It's identical to SiteSubtitleEQ.
func SiteSubtitle(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldSiteSubtitle, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldUpdatedAt, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContainsFold(FieldDomain, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldUserID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContainsFold(FieldStatus, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContainsFold(FieldNotes, v))
}

// SiteNameEQ applies the EQ predicate on the "site_name" field.
func SiteNameEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldSiteName, v))
}

// SiteNameNEQ applies the NEQ predicate on the "site_name" field.
func SiteNameNEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldSiteName, v))
}

// SiteNameIn applies the In predicate on the "site_name" field.
func SiteNameIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldSiteName, vs...))
}

// SiteNameNotIn applies the NotIn predicate on the "site_name" field.
func SiteNameNotIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldSiteName, vs...))
}

// SiteNameGT applies the GT predicate on the "site_name" field.
func SiteNameGT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldSiteName, v))
}

// SiteNameGTE applies the GTE predicate on the "site_name" field.
func SiteNameGTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldSiteName, v))
}

// SiteNameLT applies the LT predicate on the "site_name" field.
func SiteNameLT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldSiteName, v))
}

// SiteNameLTE applies the LTE predicate on the "site_name" field.
func SiteNameLTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldSiteName, v))
}

// SiteNameContains applies the Contains predicate on the "site_name" field.
func SiteNameContains(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContains(FieldSiteName, v))
}

// SiteNameHasPrefix applies the HasPrefix predicate on the "site_name" field.
func SiteNameHasPrefix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasPrefix(FieldSiteName, v))
}

// SiteNameHasSuffix applies the HasSuffix predicate on the "site_name" field.
func SiteNameHasSuffix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasSuffix(FieldSiteName, v))
}

// SiteNameIsNil applies the IsNil predicate on the "site_name" field.
func SiteNameIsNil() predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIsNull(FieldSiteName))
}

// SiteNameNotNil applies the NotNil predicate on the "site_name" field.
func SiteNameNotNil() predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotNull(FieldSiteName))
}

// SiteNameEqualFold applies the EqualFold predicate on the "site_name" field.
func SiteNameEqualFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEqualFold(FieldSiteName, v))
}

// SiteNameContainsFold applies the ContainsFold predicate on the "site_name" field.
func SiteNameContainsFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContainsFold(FieldSiteName, v))
}

// SiteLogoEQ applies the EQ predicate on the "site_logo" field.
func SiteLogoEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldSiteLogo, v))
}

// SiteLogoNEQ applies the NEQ predicate on the "site_logo" field.
func SiteLogoNEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldSiteLogo, v))
}

// SiteLogoIn applies the In predicate on the "site_logo" field.
func SiteLogoIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldSiteLogo, vs...))
}

// SiteLogoNotIn applies the NotIn predicate on the "site_logo" field.
func SiteLogoNotIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldSiteLogo, vs...))
}

// SiteLogoGT applies the GT predicate on the "site_logo" field.
func SiteLogoGT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldSiteLogo, v))
}

// SiteLogoGTE applies the GTE predicate on the "site_logo" field.
func SiteLogoGTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldSiteLogo, v))
}

// SiteLogoLT applies the LT predicate on the "site_logo" field.
func SiteLogoLT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldSiteLogo, v))
}

// SiteLogoLTE applies the LTE predicate on the "site_logo" field.
func SiteLogoLTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldSiteLogo, v))
}

// SiteLogoContains applies the Contains predicate on the "site_logo" field.
func SiteLogoContains(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContains(FieldSiteLogo, v))
}

// SiteLogoHasPrefix applies the HasPrefix predicate on the "site_logo" field.
func SiteLogoHasPrefix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasPrefix(FieldSiteLogo, v))
}

// SiteLogoHasSuffix applies the HasSuffix predicate on the "site_logo" field.
func SiteLogoHasSuffix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasSuffix(FieldSiteLogo, v))
}

// SiteLogoIsNil applies the IsNil predicate on the "site_logo" field.
func SiteLogoIsNil() predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIsNull(FieldSiteLogo))
}

// SiteLogoNotNil applies the NotNil predicate on the "site_logo" field.
func SiteLogoNotNil() predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotNull(FieldSiteLogo))
}

// SiteLogoEqualFold applies the EqualFold predicate on the "site_logo" field.
func SiteLogoEqualFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEqualFold(FieldSiteLogo, v))
}

// SiteLogoContainsFold applies the ContainsFold predicate on the "site_logo" field.
func SiteLogoContainsFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContainsFold(FieldSiteLogo, v))
}

// SiteSubtitleEQ applies the EQ predicate on the "site_subtitle" field.
func SiteSubtitleEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEQ(FieldSiteSubtitle, v))
}

// SiteSubtitleNEQ applies the NEQ predicate on the "site_subtitle" field.
func SiteSubtitleNEQ(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNEQ(FieldSiteSubtitle, v))
}

// SiteSubtitleIn applies the In predicate on the "site_subtitle" field.
func SiteSubtitleIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIn(FieldSiteSubtitle, vs...))
}

// SiteSubtitleNotIn applies the NotIn predicate on the "site_subtitle" field.
func SiteSubtitleNotIn(vs ...string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotIn(FieldSiteSubtitle, vs...))
}

// SiteSubtitleGT applies the GT predicate on the "site_subtitle" field.
func SiteSubtitleGT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGT(FieldSiteSubtitle, v))
}

// SiteSubtitleGTE applies the GTE predicate on the "site_subtitle" field.
func SiteSubtitleGTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldGTE(FieldSiteSubtitle, v))
}

// SiteSubtitleLT applies the LT predicate on the "site_subtitle" field.
func SiteSubtitleLT(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLT(FieldSiteSubtitle, v))
}

// SiteSubtitleLTE applies the LTE predicate on the "site_subtitle" field.
func SiteSubtitleLTE(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldLTE(FieldSiteSubtitle, v))
}

// SiteSubtitleContains applies the Contains predicate on the "site_subtitle" field.
func SiteSubtitleContains(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContains(FieldSiteSubtitle, v))
}

// SiteSubtitleHasPrefix applies the HasPrefix predicate on the "site_subtitle" field.
func SiteSubtitleHasPrefix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasPrefix(FieldSiteSubtitle, v))
}

// SiteSubtitleHasSuffix applies the HasSuffix predicate on the "site_subtitle" field.
func SiteSubtitleHasSuffix(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldHasSuffix(FieldSiteSubtitle, v))
}

// SiteSubtitleIsNil applies the IsNil predicate on the "site_subtitle" field.
func SiteSubtitleIsNil() predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldIsNull(FieldSiteSubtitle))
}

// SiteSubtitleNotNil applies the NotNil predicate on the "site_subtitle" field.
func SiteSubtitleNotNil() predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldNotNull(FieldSiteSubtitle))
}

// SiteSubtitleEqualFold applies the EqualFold predicate on the "site_subtitle" field.
func SiteSubtitleEqualFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldEqualFold(FieldSiteSubtitle, v))
}

// SiteSubtitleContainsFold applies the ContainsFold predicate on the "site_subtitle" field.
func SiteSubtitleContainsFold(v string) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.FieldContainsFold(FieldSiteSubtitle, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResellerDomain) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResellerDomain) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResellerDomain) predicate.ResellerDomain {
	return predicate.ResellerDomain(sql.NotPredicates(p))
}
