// Code generated by ent, DO NOT EDIT.

package resellerplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the resellerplan type in the database.
	Label = "reseller_plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldCreditRate holds the string denoting the credit_rate field in the database.
	FieldCreditRate = "credit_rate"
	// FieldConcurrencyBonus holds the string denoting the concurrency_bonus field in the database.
	FieldConcurrencyBonus = "concurrency_bonus"
	// FieldRpmLimit holds the string denoting the rpm_limit field in the database.
	FieldRpmLimit = "rpm_limit"
	// FieldMaxDomains holds the string denoting the max_domains field in the database.
	FieldMaxDomains = "max_domains"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// FieldAllowedGroupIds holds the string denoting the allowed_group_ids field in the database.
	FieldAllowedGroupIds = "allowed_group_ids"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// Table holds the table name of the resellerplan in the database.
	Table = "reseller_plans"
)

// Columns holds all SQL columns for resellerplan fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLevel,
	FieldName,
	FieldPrice,
	FieldCreditRate,
	FieldConcurrencyBonus,
	FieldRpmLimit,
	FieldMaxDomains,
	FieldValidityDays,
	FieldAllowedGroupIds,
	FieldEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator func(int) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreditRate holds the default value on creation for the "credit_rate" field.
	DefaultCreditRate float64
	// DefaultConcurrencyBonus holds the default value on creation for the "concurrency_bonus" field.
	DefaultConcurrencyBonus int
	// ConcurrencyBonusValidator is a validator for the "concurrency_bonus" field. It is called by the builders before save.
	ConcurrencyBonusValidator func(int) error
	// DefaultRpmLimit holds the default value on creation for the "rpm_limit" field.
	DefaultRpmLimit int
	// RpmLimitValidator is a validator for the "rpm_limit" field. It is called by the builders before save.
	RpmLimitValidator func(int) error
	// DefaultMaxDomains holds the default value on creation for the "max_domains" field.
	DefaultMaxDomains int
	// MaxDomainsValidator is a validator for the "max_domains" field. It is called by the builders before save.
	MaxDomainsValidator func(int) error
	// DefaultValidityDays holds the default value on creation for the "validity_days" field.
	DefaultValidityDays int
	// ValidityDaysValidator is a validator for the "validity_days" field. It is called by the builders before save.
	ValidityDaysValidator func(int) error
	// DefaultAllowedGroupIds holds the default value on creation for the "allowed_group_ids" field.
	DefaultAllowedGroupIds []int64
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the ResellerPlan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByCreditRate orders the results by the credit_rate field.
func ByCreditRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditRate, opts...).ToFunc()
}

// ByConcurrencyBonus orders the results by the concurrency_bonus field.
func ByConcurrencyBonus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrencyBonus, opts...).ToFunc()
}

// ByRpmLimit orders the results by the rpm_limit field.
func ByRpmLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRpmLimit, opts...).ToFunc()
}

// ByMaxDomains orders the results by the max_domains field.
func ByMaxDomains(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxDomains, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}
