// Code generated by ent, DO NOT EDIT.

package resellerplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldLevel, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldName, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldPrice, v))
}

// CreditRate applies equality check predicate on the "credit_rate" field. It's identical to CreditRateEQ.
func CreditRate(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldCreditRate, v))
}

// ConcurrencyBonus applies equality check predicate on the "concurrency_bonus" field. It's identical to ConcurrencyBonusEQ.
func ConcurrencyBonus(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldConcurrencyBonus, v))
}

// RpmLimit applies equality check predicate on the "rpm_limit" field. It's identical to RpmLimitEQ.
func RpmLimit(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldRpmLimit, v))
}

// MaxDomains applies equality check predicate on the "max_domains" field. It's identical to MaxDomainsEQ.
func MaxDomains(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldMaxDomains, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldValidityDays, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldLevel, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldContainsFold(FieldName, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldPrice, v))
}

// CreditRateEQ applies the EQ predicate on the "credit_rate" field.
func CreditRateEQ(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldCreditRate, v))
}

// CreditRateNEQ applies the NEQ predicate on the "credit_rate" field.
func CreditRateNEQ(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldCreditRate, v))
}

// CreditRateIn applies the In predicate on the "credit_rate" field.
func CreditRateIn(vs ...float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldCreditRate, vs...))
}

// CreditRateNotIn applies the NotIn predicate on the "credit_rate" field.
func CreditRateNotIn(vs ...float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldCreditRate, vs...))
}

// CreditRateGT applies the GT predicate on the "credit_rate" field.
func CreditRateGT(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldCreditRate, v))
}

// CreditRateGTE applies the GTE predicate on the "credit_rate" field.
func CreditRateGTE(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldCreditRate, v))
}

// CreditRateLT applies the LT predicate on the "credit_rate" field.
func CreditRateLT(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldCreditRate, v))
}

// CreditRateLTE applies the LTE predicate on the "credit_rate" field.
func CreditRateLTE(v float64) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldCreditRate, v))
}

// ConcurrencyBonusEQ applies the EQ predicate on the "concurrency_bonus" field.
func ConcurrencyBonusEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldConcurrencyBonus, v))
}

// ConcurrencyBonusNEQ applies the NEQ predicate on the "concurrency_bonus" field.
func ConcurrencyBonusNEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldConcurrencyBonus, v))
}

// ConcurrencyBonusIn applies the In predicate on the "concurrency_bonus" field.
func ConcurrencyBonusIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldConcurrencyBonus, vs...))
}

// ConcurrencyBonusNotIn applies the NotIn predicate on the "concurrency_bonus" field.
func ConcurrencyBonusNotIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldConcurrencyBonus, vs...))
}

// ConcurrencyBonusGT applies the GT predicate on the "concurrency_bonus" field.
func ConcurrencyBonusGT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldConcurrencyBonus, v))
}

// ConcurrencyBonusGTE applies the GTE predicate on the "concurrency_bonus" field.
func ConcurrencyBonusGTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldConcurrencyBonus, v))
}

// ConcurrencyBonusLT applies the LT predicate on the "concurrency_bonus" field.
func ConcurrencyBonusLT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldConcurrencyBonus, v))
}

// ConcurrencyBonusLTE applies the LTE predicate on the "concurrency_bonus" field.
func ConcurrencyBonusLTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldConcurrencyBonus, v))
}

// RpmLimitEQ applies the EQ predicate on the "rpm_limit" field.
func RpmLimitEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldRpmLimit, v))
}

// RpmLimitNEQ applies the NEQ predicate on the "rpm_limit" field.
func RpmLimitNEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldRpmLimit, v))
}

// RpmLimitIn applies the In predicate on the "rpm_limit" field.
func RpmLimitIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldRpmLimit, vs...))
}

// RpmLimitNotIn applies the NotIn predicate on the "rpm_limit" field.
func RpmLimitNotIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldRpmLimit, vs...))
}

// RpmLimitGT applies the GT predicate on the "rpm_limit" field.
func RpmLimitGT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldRpmLimit, v))
}

// RpmLimitGTE applies the GTE predicate on the "rpm_limit" field.
func RpmLimitGTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldRpmLimit, v))
}

// RpmLimitLT applies the LT predicate on the "rpm_limit" field.
func RpmLimitLT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldRpmLimit, v))
}

// RpmLimitLTE applies the LTE predicate on the "rpm_limit" field.
func RpmLimitLTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldRpmLimit, v))
}

// MaxDomainsEQ applies the EQ predicate on the "max_domains" field.
func MaxDomainsEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldMaxDomains, v))
}

// MaxDomainsNEQ applies the NEQ predicate on the "max_domains" field.
func MaxDomainsNEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldMaxDomains, v))
}

// MaxDomainsIn applies the In predicate on the "max_domains" field.
func MaxDomainsIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldMaxDomains, vs...))
}

// MaxDomainsNotIn applies the NotIn predicate on the "max_domains" field.
func MaxDomainsNotIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldMaxDomains, vs...))
}

// MaxDomainsGT applies the GT predicate on the "max_domains" field.
func MaxDomainsGT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldMaxDomains, v))
}

// MaxDomainsGTE applies the GTE predicate on the "max_domains" field.
func MaxDomainsGTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldMaxDomains, v))
}

// MaxDomainsLT applies the LT predicate on the "max_domains" field.
func MaxDomainsLT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldMaxDomains, v))
}

// MaxDomainsLTE applies the LTE predicate on the "max_domains" field.
func MaxDomainsLTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldMaxDomains, v))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldLTE(FieldValidityDays, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResellerPlan) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResellerPlan) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResellerPlan) predicate.ResellerPlan {
	return predicate.ResellerPlan(sql.NotPredicates(p))
}
