// Code generated by ent, DO NOT EDIT.

package viptier

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the viptier type in the database.
	Label = "vip_tier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldMinSpendUsd holds the string denoting the min_spend_usd field in the database.
	FieldMinSpendUsd = "min_spend_usd"
	// FieldRateMultiplier holds the string denoting the rate_multiplier field in the database.
	FieldRateMultiplier = "rate_multiplier"
	// FieldConcurrency holds the string denoting the concurrency field in the database.
	FieldConcurrency = "concurrency"
	// FieldRpmLimit holds the string denoting the rpm_limit field in the database.
	FieldRpmLimit = "rpm_limit"
	// FieldUnlimitedRpm holds the string denoting the unlimited_rpm field in the database.
	FieldUnlimitedRpm = "unlimited_rpm"
	// FieldUnlimitedConcurrency holds the string denoting the unlimited_concurrency field in the database.
	FieldUnlimitedConcurrency = "unlimited_concurrency"
	// FieldGraceDays holds the string denoting the grace_days field in the database.
	FieldGraceDays = "grace_days"
	// FieldBadgeColor holds the string denoting the badge_color field in the database.
	FieldBadgeColor = "badge_color"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the viptier in the database.
	Table = "vip_tiers"
)

// Columns holds all SQL columns for viptier fields.
var Columns = []string{
	FieldID,
	FieldLevel,
	FieldName,
	FieldMinSpendUsd,
	FieldRateMultiplier,
	FieldConcurrency,
	FieldRpmLimit,
	FieldUnlimitedRpm,
	FieldUnlimitedConcurrency,
	FieldGraceDays,
	FieldBadgeColor,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator func(int) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultRateMultiplier holds the default value on creation for the "rate_multiplier" field.
	DefaultRateMultiplier float64
	// DefaultConcurrency holds the default value on creation for the "concurrency" field.
	DefaultConcurrency int
	// ConcurrencyValidator is a validator for the "concurrency" field. It is called by the builders before save.
	ConcurrencyValidator func(int) error
	// DefaultRpmLimit holds the default value on creation for the "rpm_limit" field.
	DefaultRpmLimit int
	// RpmLimitValidator is a validator for the "rpm_limit" field. It is called by the builders before save.
	RpmLimitValidator func(int) error
	// DefaultUnlimitedRpm holds the default value on creation for the "unlimited_rpm" field.
	DefaultUnlimitedRpm bool
	// DefaultUnlimitedConcurrency holds the default value on creation for the "unlimited_concurrency" field.
	DefaultUnlimitedConcurrency bool
	// DefaultGraceDays holds the default value on creation for the "grace_days" field.
	DefaultGraceDays int
	// GraceDaysValidator is a validator for the "grace_days" field. It is called by the builders before save.
	GraceDaysValidator func(int) error
	// DefaultBadgeColor holds the default value on creation for the "badge_color" field.
	DefaultBadgeColor string
	// BadgeColorValidator is a validator for the "badge_color" field. It is called by the builders before save.
	BadgeColorValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the VIPTier queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByMinSpendUsd orders the results by the min_spend_usd field.
func ByMinSpendUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinSpendUsd, opts...).ToFunc()
}

// ByRateMultiplier orders the results by the rate_multiplier field.
func ByRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateMultiplier, opts...).ToFunc()
}

// ByConcurrency orders the results by the concurrency field.
func ByConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrency, opts...).ToFunc()
}

// ByRpmLimit orders the results by the rpm_limit field.
func ByRpmLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRpmLimit, opts...).ToFunc()
}

// ByUnlimitedRpm orders the results by the unlimited_rpm field.
func ByUnlimitedRpm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnlimitedRpm, opts...).ToFunc()
}

// ByUnlimitedConcurrency orders the results by the unlimited_concurrency field.
func ByUnlimitedConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnlimitedConcurrency, opts...).ToFunc()
}

// ByGraceDays orders the results by the grace_days field.
func ByGraceDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGraceDays, opts...).ToFunc()
}

// ByBadgeColor orders the results by the badge_color field.
func ByBadgeColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBadgeColor, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
