// Code generated by ent, DO NOT EDIT.

package viptier

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldID, id))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldLevel, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldName, v))
}

// MinSpendUsd applies equality check predicate on the "min_spend_usd" field. It's identical to MinSpendUsdEQ.
func MinSpendUsd(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldMinSpendUsd, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldRateMultiplier, v))
}

// Concurrency applies equality check predicate on the "concurrency" field. It's identical to ConcurrencyEQ.
func Concurrency(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldConcurrency, v))
}

// GraceDays applies equality check predicate on the "grace_days" field. It's identical to GraceDaysEQ.
func GraceDays(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldGraceDays, v))
}

// BadgeColor applies equality check predicate on the "badge_color" field. It's identical to BadgeColorEQ.
func BadgeColor(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldBadgeColor, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldUpdatedAt, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldLevel, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldContainsFold(FieldName, v))
}

// MinSpendUsdEQ applies the EQ predicate on the "min_spend_usd" field.
func MinSpendUsdEQ(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldMinSpendUsd, v))
}

// MinSpendUsdNEQ applies the NEQ predicate on the "min_spend_usd" field.
func MinSpendUsdNEQ(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldMinSpendUsd, v))
}

// MinSpendUsdIn applies the In predicate on the "min_spend_usd" field.
func MinSpendUsdIn(vs ...float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldMinSpendUsd, vs...))
}

// MinSpendUsdNotIn applies the NotIn predicate on the "min_spend_usd" field.
func MinSpendUsdNotIn(vs ...float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldMinSpendUsd, vs...))
}

// MinSpendUsdGT applies the GT predicate on the "min_spend_usd" field.
func MinSpendUsdGT(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldMinSpendUsd, v))
}

// MinSpendUsdGTE applies the GTE predicate on the "min_spend_usd" field.
func MinSpendUsdGTE(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldMinSpendUsd, v))
}

// MinSpendUsdLT applies the LT predicate on the "min_spend_usd" field.
func MinSpendUsdLT(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldMinSpendUsd, v))
}

// MinSpendUsdLTE applies the LTE predicate on the "min_spend_usd" field.
func MinSpendUsdLTE(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldMinSpendUsd, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldRateMultiplier, v))
}

// ConcurrencyEQ applies the EQ predicate on the "concurrency" field.
func ConcurrencyEQ(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldConcurrency, v))
}

// ConcurrencyNEQ applies the NEQ predicate on the "concurrency" field.
func ConcurrencyNEQ(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldConcurrency, v))
}

// ConcurrencyIn applies the In predicate on the "concurrency" field.
func ConcurrencyIn(vs ...int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldConcurrency, vs...))
}

// ConcurrencyNotIn applies the NotIn predicate on the "concurrency" field.
func ConcurrencyNotIn(vs ...int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldConcurrency, vs...))
}

// ConcurrencyGT applies the GT predicate on the "concurrency" field.
func ConcurrencyGT(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldConcurrency, v))
}

// ConcurrencyGTE applies the GTE predicate on the "concurrency" field.
func ConcurrencyGTE(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldConcurrency, v))
}

// ConcurrencyLT applies the LT predicate on the "concurrency" field.
func ConcurrencyLT(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldConcurrency, v))
}

// ConcurrencyLTE applies the LTE predicate on the "concurrency" field.
func ConcurrencyLTE(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldConcurrency, v))
}

// GraceDaysEQ applies the EQ predicate on the "grace_days" field.
func GraceDaysEQ(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldGraceDays, v))
}

// GraceDaysNEQ applies the NEQ predicate on the "grace_days" field.
func GraceDaysNEQ(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldGraceDays, v))
}

// GraceDaysIn applies the In predicate on the "grace_days" field.
func GraceDaysIn(vs ...int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldGraceDays, vs...))
}

// GraceDaysNotIn applies the NotIn predicate on the "grace_days" field.
func GraceDaysNotIn(vs ...int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldGraceDays, vs...))
}

// GraceDaysGT applies the GT predicate on the "grace_days" field.
func GraceDaysGT(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldGraceDays, v))
}

// GraceDaysGTE applies the GTE predicate on the "grace_days" field.
func GraceDaysGTE(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldGraceDays, v))
}

// GraceDaysLT applies the LT predicate on the "grace_days" field.
func GraceDaysLT(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldGraceDays, v))
}

// GraceDaysLTE applies the LTE predicate on the "grace_days" field.
func GraceDaysLTE(v int) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldGraceDays, v))
}

// BadgeColorEQ applies the EQ predicate on the "badge_color" field.
func BadgeColorEQ(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldBadgeColor, v))
}

// BadgeColorNEQ applies the NEQ predicate on the "badge_color" field.
func BadgeColorNEQ(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldBadgeColor, v))
}

// BadgeColorIn applies the In predicate on the "badge_color" field.
func BadgeColorIn(vs ...string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldBadgeColor, vs...))
}

// BadgeColorNotIn applies the NotIn predicate on the "badge_color" field.
func BadgeColorNotIn(vs ...string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldBadgeColor, vs...))
}

// BadgeColorGT applies the GT predicate on the "badge_color" field.
func BadgeColorGT(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldBadgeColor, v))
}

// BadgeColorGTE applies the GTE predicate on the "badge_color" field.
func BadgeColorGTE(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldBadgeColor, v))
}

// BadgeColorLT applies the LT predicate on the "badge_color" field.
func BadgeColorLT(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldBadgeColor, v))
}

// BadgeColorLTE applies the LTE predicate on the "badge_color" field.
func BadgeColorLTE(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldBadgeColor, v))
}

// BadgeColorContains applies the Contains predicate on the "badge_color" field.
func BadgeColorContains(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldContains(FieldBadgeColor, v))
}

// BadgeColorHasPrefix applies the HasPrefix predicate on the "badge_color" field.
func BadgeColorHasPrefix(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldHasPrefix(FieldBadgeColor, v))
}

// BadgeColorHasSuffix applies the HasSuffix predicate on the "badge_color" field.
func BadgeColorHasSuffix(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldHasSuffix(FieldBadgeColor, v))
}

// BadgeColorEqualFold applies the EqualFold predicate on the "badge_color" field.
func BadgeColorEqualFold(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEqualFold(FieldBadgeColor, v))
}

// BadgeColorContainsFold applies the ContainsFold predicate on the "badge_color" field.
func BadgeColorContainsFold(v string) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldContainsFold(FieldBadgeColor, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VIPTier {
	return predicate.VIPTier(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VIPTier) predicate.VIPTier {
	return predicate.VIPTier(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VIPTier) predicate.VIPTier {
	return predicate.VIPTier(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VIPTier) predicate.VIPTier {
	return predicate.VIPTier(sql.NotPredicates(p))
}
