// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resellerdomain"
)

// ResellerDomainUpdate is the builder for updating ResellerDomain entities.
type ResellerDomainUpdate struct {
	config
	hooks    []Hook
	mutation *ResellerDomainMutation
}

// Where appends a list predicates to the ResellerDomainUpdate builder.
func (_u *ResellerDomainUpdate) Where(ps ...predicate.ResellerDomain) *ResellerDomainUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResellerDomainUpdate) SetUpdatedAt(v time.Time) *ResellerDomainUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *ResellerDomainUpdate) SetDomain(v string) *ResellerDomainUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableDomain(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResellerDomainUpdate) SetUserID(v int64) *ResellerDomainUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableUserID(v *int64) *ResellerDomainUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResellerDomainUpdate) AddUserID(v int64) *ResellerDomainUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResellerDomainUpdate) SetStatus(v string) *ResellerDomainUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableStatus(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ResellerDomainUpdate) SetNotes(v string) *ResellerDomainUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableNotes(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetSiteName sets the "site_name" field.
func (_u *ResellerDomainUpdate) SetSiteName(v string) *ResellerDomainUpdate {
	_u.mutation.SetSiteName(v)
	return _u
}

// SetNillableSiteName sets the "site_name" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableSiteName(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetSiteName(*v)
	}
	return _u
}

// ClearSiteName clears the value of the "site_name" field.
func (_u *ResellerDomainUpdate) ClearSiteName() *ResellerDomainUpdate {
	_u.mutation.ClearSiteName()
	return _u
}

// SetSiteLogo sets the "site_logo" field.
func (_u *ResellerDomainUpdate) SetSiteLogo(v string) *ResellerDomainUpdate {
	_u.mutation.SetSiteLogo(v)
	return _u
}

// SetNillableSiteLogo sets the "site_logo" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableSiteLogo(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetSiteLogo(*v)
	}
	return _u
}

// ClearSiteLogo clears the value of the "site_logo" field.
func (_u *ResellerDomainUpdate) ClearSiteLogo() *ResellerDomainUpdate {
	_u.mutation.ClearSiteLogo()
	return _u
}

// SetSiteSubtitle sets the "site_subtitle" field.
func (_u *ResellerDomainUpdate) SetSiteSubtitle(v string) *ResellerDomainUpdate {
	_u.mutation.SetSiteSubtitle(v)
	return _u
}

// SetNillableSiteSubtitle sets the "site_subtitle" field if the given value is not nil.
func (_u *ResellerDomainUpdate) SetNillableSiteSubtitle(v *string) *ResellerDomainUpdate {
	if v != nil {
		_u.SetSiteSubtitle(*v)
	}
	return _u
}

// ClearSiteSubtitle clears the value of the "site_subtitle" field.
func (_u *ResellerDomainUpdate) ClearSiteSubtitle() *ResellerDomainUpdate {
	_u.mutation.ClearSiteSubtitle()
	return _u
}

// Mutation returns the ResellerDomainMutation object of the builder.
func (_u *ResellerDomainUpdate) Mutation() *ResellerDomainMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResellerDomainUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResellerDomainUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResellerDomainUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResellerDomainUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResellerDomainUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resellerdomain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResellerDomainUpdate) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := resellerdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resellerdomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteName(); ok {
		if err := resellerdomain.SiteNameValidator(v); err != nil {
			return &ValidationError{Name: "site_name", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.site_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteSubtitle(); ok {
		if err := resellerdomain.SiteSubtitleValidator(v); err != nil {
			return &ValidationError{Name: "site_subtitle", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.site_subtitle": %w`, err)}
		}
	}
	return nil
}

func (_u *ResellerDomainUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resellerdomain.Table, resellerdomain.Columns, sqlgraph.NewFieldSpec(resellerdomain.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerdomain.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(resellerdomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resellerdomain.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resellerdomain.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resellerdomain.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(resellerdomain.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteName(); ok {
		_spec.SetField(resellerdomain.FieldSiteName, field.TypeString, value)
	}
	if _u.mutation.SiteNameCleared() {
		_spec.ClearField(resellerdomain.FieldSiteName, field.TypeString)
	}
	if value, ok := _u.mutation.SiteLogo(); ok {
		_spec.SetField(resellerdomain.FieldSiteLogo, field.TypeString, value)
	}
	if _u.mutation.SiteLogoCleared() {
		_spec.ClearField(resellerdomain.FieldSiteLogo, field.TypeString)
	}
	if value, ok := _u.mutation.SiteSubtitle(); ok {
		_spec.SetField(resellerdomain.FieldSiteSubtitle, field.TypeString, value)
	}
	if _u.mutation.SiteSubtitleCleared() {
		_spec.ClearField(resellerdomain.FieldSiteSubtitle, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resellerdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResellerDomainUpdateOne is the builder for updating a single ResellerDomain entity.
type ResellerDomainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResellerDomainMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResellerDomainUpdateOne) SetUpdatedAt(v time.Time) *ResellerDomainUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *ResellerDomainUpdateOne) SetDomain(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableDomain(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResellerDomainUpdateOne) SetUserID(v int64) *ResellerDomainUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableUserID(v *int64) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResellerDomainUpdateOne) AddUserID(v int64) *ResellerDomainUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResellerDomainUpdateOne) SetStatus(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableStatus(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ResellerDomainUpdateOne) SetNotes(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableNotes(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetSiteName sets the "site_name" field.
func (_u *ResellerDomainUpdateOne) SetSiteName(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetSiteName(v)
	return _u
}

// SetNillableSiteName sets the "site_name" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableSiteName(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetSiteName(*v)
	}
	return _u
}

// ClearSiteName clears the value of the "site_name" field.
func (_u *ResellerDomainUpdateOne) ClearSiteName() *ResellerDomainUpdateOne {
	_u.mutation.ClearSiteName()
	return _u
}

// SetSiteLogo sets the "site_logo" field.
func (_u *ResellerDomainUpdateOne) SetSiteLogo(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetSiteLogo(v)
	return _u
}

// SetNillableSiteLogo sets the "site_logo" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableSiteLogo(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetSiteLogo(*v)
	}
	return _u
}

// ClearSiteLogo clears the value of the "site_logo" field.
func (_u *ResellerDomainUpdateOne) ClearSiteLogo() *ResellerDomainUpdateOne {
	_u.mutation.ClearSiteLogo()
	return _u
}

// SetSiteSubtitle sets the "site_subtitle" field.
func (_u *ResellerDomainUpdateOne) SetSiteSubtitle(v string) *ResellerDomainUpdateOne {
	_u.mutation.SetSiteSubtitle(v)
	return _u
}

// SetNillableSiteSubtitle sets the "site_subtitle" field if the given value is not nil.
func (_u *ResellerDomainUpdateOne) SetNillableSiteSubtitle(v *string) *ResellerDomainUpdateOne {
	if v != nil {
		_u.SetSiteSubtitle(*v)
	}
	return _u
}

// ClearSiteSubtitle clears the value of the "site_subtitle" field.
func (_u *ResellerDomainUpdateOne) ClearSiteSubtitle() *ResellerDomainUpdateOne {
	_u.mutation.ClearSiteSubtitle()
	return _u
}

// Mutation returns the ResellerDomainMutation object of the builder.
func (_u *ResellerDomainUpdateOne) Mutation() *ResellerDomainMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResellerDomainUpdate builder.
func (_u *ResellerDomainUpdateOne) Where(ps ...predicate.ResellerDomain) *ResellerDomainUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResellerDomainUpdateOne) Select(field string, fields ...string) *ResellerDomainUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResellerDomain entity.
func (_u *ResellerDomainUpdateOne) Save(ctx context.Context) (*ResellerDomain, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResellerDomainUpdateOne) SaveX(ctx context.Context) *ResellerDomain {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResellerDomainUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResellerDomainUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResellerDomainUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resellerdomain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResellerDomainUpdateOne) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := resellerdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := resellerdomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteName(); ok {
		if err := resellerdomain.SiteNameValidator(v); err != nil {
			return &ValidationError{Name: "site_name", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.site_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteSubtitle(); ok {
		if err := resellerdomain.SiteSubtitleValidator(v); err != nil {
			return &ValidationError{Name: "site_subtitle", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.site_subtitle": %w`, err)}
		}
	}
	return nil
}

func (_u *ResellerDomainUpdateOne) sqlSave(ctx context.Context) (_node *ResellerDomain, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resellerdomain.Table, resellerdomain.Columns, sqlgraph.NewFieldSpec(resellerdomain.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResellerDomain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resellerdomain.FieldID)
		for _, f := range fields {
			if !resellerdomain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resellerdomain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerdomain.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(resellerdomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resellerdomain.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resellerdomain.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resellerdomain.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(resellerdomain.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteName(); ok {
		_spec.SetField(resellerdomain.FieldSiteName, field.TypeString, value)
	}
	if _u.mutation.SiteNameCleared() {
		_spec.ClearField(resellerdomain.FieldSiteName, field.TypeString)
	}
	if value, ok := _u.mutation.SiteLogo(); ok {
		_spec.SetField(resellerdomain.FieldSiteLogo, field.TypeString, value)
	}
	if _u.mutation.SiteLogoCleared() {
		_spec.ClearField(resellerdomain.FieldSiteLogo, field.TypeString)
	}
	if value, ok := _u.mutation.SiteSubtitle(); ok {
		_spec.SetField(resellerdomain.FieldSiteSubtitle, field.TypeString, value)
	}
	if _u.mutation.SiteSubtitleCleared() {
		_spec.ClearField(resellerdomain.FieldSiteSubtitle, field.TypeString)
	}
	_node = &ResellerDomain{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resellerdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
