// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/resellerplan"
)

// ResellerPlanUpdate is the builder for updating ResellerPlan entities.
type ResellerPlanUpdate struct {
	config
	hooks    []Hook
	mutation *ResellerPlanMutation
}

// Where appends a list predicates to the ResellerPlanUpdate builder.
func (_u *ResellerPlanUpdate) Where(ps ...predicate.ResellerPlan) *ResellerPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResellerPlanUpdate) SetUpdatedAt(v time.Time) *ResellerPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLevel sets the "level" field.
func (_u *ResellerPlanUpdate) SetLevel(v int) *ResellerPlanUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *ResellerPlanUpdate) SetNillableLevel(v *int) *ResellerPlanUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *ResellerPlanUpdate) AddLevel(v int) *ResellerPlanUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ResellerPlanUpdate) SetName(v string) *ResellerPlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResellerPlanUpdate) SetNillableName(v *string) *ResellerPlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *ResellerPlanUpdate) SetPrice(v float64) *ResellerPlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ResellerPlanUpdate) SetNillablePrice(v *float64) *ResellerPlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *ResellerPlanUpdate) AddPrice(v float64) *ResellerPlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetCreditRate sets the "credit_rate" field.
func (_u *ResellerPlanUpdate) SetCreditRate(v float64) *ResellerPlanUpdate {
	_u.mutation.ResetCreditRate()
	_u.mutation.SetCreditRate(v)
	return _u
}

// SetNillableCreditRate sets the "credit_rate" field if the given value is not nil.
func (_u *ResellerPlanUpdate) SetNillableCreditRate(v *float64) *ResellerPlanUpdate {
	if v != nil {
		_u.SetCreditRate(*v)
	}
	return _u
}

// AddCreditRate adds value to the "credit_rate" field.
func (_u *ResellerPlanUpdate) AddCreditRate(v float64) *ResellerPlanUpdate {
	_u.mutation.AddCreditRate(v)
	return _u
}

// SetConcurrencyBonus sets the "concurrency_bonus" field.
func (_u *ResellerPlanUpdate) SetConcurrencyBonus(v int) *ResellerPlanUpdate {
	_u.mutation.ResetConcurrencyBonus()
	_u.mutation.SetConcurrencyBonus(v)
	return _u
}

// SetNillableConcurrencyBonus sets the "concurrency_bonus" field if the given value is not nil.
func (_u *ResellerPlanUpdate) SetNillableConcurrencyBonus(v *int) *ResellerPlanUpdate {
	if v != nil {
		_u.SetConcurrencyBonus(*v)
	}
	return _u
}

// AddConcurrencyBonus adds value to the "concurrency_bonus" field.
func (_u *ResellerPlanUpdate) AddConcurrencyBonus(v int) *ResellerPlanUpdate {
	_u.mutation.AddConcurrencyBonus(v)
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *ResellerPlanUpdate) SetRpmLimit(v int) *ResellerPlanUpdate {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *ResellerPlanUpdate) SetNillableRpmLimit(v *int) *ResellerPlanUpdate {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *ResellerPlanUpdate) AddRpmLimit(v int) *ResellerPlanUpdate {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetMaxDomains sets the "max_domains" field.
func (_u *ResellerPlanUpdate) SetMaxDomains(v int) *ResellerPlanUpdate {
	_u.mutation.ResetMaxDomains()
	_u.mutation.SetMaxDomains(v)
	return _u
}

// SetNillableMaxDomains sets the "max_domains" field if the given value is not nil.
func (_u *ResellerPlanUpdate) SetNillableMaxDomains(v *int) *ResellerPlanUpdate {
	if v != nil {
		_u.SetMaxDomains(*v)
	}
	return _u
}

// AddMaxDomains adds value to the "max_domains" field.
func (_u *ResellerPlanUpdate) AddMaxDomains(v int) *ResellerPlanUpdate {
	_u.mutation.AddMaxDomains(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *ResellerPlanUpdate) SetValidityDays(v int) *ResellerPlanUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *ResellerPlanUpdate) SetNillableValidityDays(v *int) *ResellerPlanUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *ResellerPlanUpdate) AddValidityDays(v int) *ResellerPlanUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (_u *ResellerPlanUpdate) SetAllowedGroupIds(v []int64) *ResellerPlanUpdate {
	_u.mutation.SetAllowedGroupIds(v)
	return _u
}

// AppendAllowedGroupIds appends value to the "allowed_group_ids" field.
func (_u *ResellerPlanUpdate) AppendAllowedGroupIds(v []int64) *ResellerPlanUpdate {
	_u.mutation.AppendAllowedGroupIds(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ResellerPlanUpdate) SetEnabled(v bool) *ResellerPlanUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ResellerPlanUpdate) SetNillableEnabled(v *bool) *ResellerPlanUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ResellerPlanMutation object of the builder.
func (_u *ResellerPlanUpdate) Mutation() *ResellerPlanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResellerPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResellerPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResellerPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResellerPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResellerPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resellerplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResellerPlanUpdate) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := resellerplan.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := resellerplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConcurrencyBonus(); ok {
		if err := resellerplan.ConcurrencyBonusValidator(v); err != nil {
			return &ValidationError{Name: "concurrency_bonus", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.concurrency_bonus": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RpmLimit(); ok {
		if err := resellerplan.RpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "rpm_limit", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.rpm_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxDomains(); ok {
		if err := resellerplan.MaxDomainsValidator(v); err != nil {
			return &ValidationError{Name: "max_domains", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.max_domains": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidityDays(); ok {
		if err := resellerplan.ValidityDaysValidator(v); err != nil {
			return &ValidationError{Name: "validity_days", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.validity_days": %w`, err)}
		}
	}
	return nil
}

func (_u *ResellerPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resellerplan.Table, resellerplan.Columns, sqlgraph.NewFieldSpec(resellerplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(resellerplan.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(resellerplan.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resellerplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(resellerplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(resellerplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditRate(); ok {
		_spec.SetField(resellerplan.FieldCreditRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditRate(); ok {
		_spec.AddField(resellerplan.FieldCreditRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ConcurrencyBonus(); ok {
		_spec.SetField(resellerplan.FieldConcurrencyBonus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyBonus(); ok {
		_spec.AddField(resellerplan.FieldConcurrencyBonus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(resellerplan.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(resellerplan.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxDomains(); ok {
		_spec.SetField(resellerplan.FieldMaxDomains, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDomains(); ok {
		_spec.AddField(resellerplan.FieldMaxDomains, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(resellerplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(resellerplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AllowedGroupIds(); ok {
		_spec.SetField(resellerplan.FieldAllowedGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, resellerplan.FieldAllowedGroupIds, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(resellerplan.FieldEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resellerplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResellerPlanUpdateOne is the builder for updating a single ResellerPlan entity.
type ResellerPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResellerPlanMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResellerPlanUpdateOne) SetUpdatedAt(v time.Time) *ResellerPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLevel sets the "level" field.
func (_u *ResellerPlanUpdateOne) SetLevel(v int) *ResellerPlanUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *ResellerPlanUpdateOne) SetNillableLevel(v *int) *ResellerPlanUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *ResellerPlanUpdateOne) AddLevel(v int) *ResellerPlanUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ResellerPlanUpdateOne) SetName(v string) *ResellerPlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResellerPlanUpdateOne) SetNillableName(v *string) *ResellerPlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *ResellerPlanUpdateOne) SetPrice(v float64) *ResellerPlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *ResellerPlanUpdateOne) SetNillablePrice(v *float64) *ResellerPlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *ResellerPlanUpdateOne) AddPrice(v float64) *ResellerPlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetCreditRate sets the "credit_rate" field.
func (_u *ResellerPlanUpdateOne) SetCreditRate(v float64) *ResellerPlanUpdateOne {
	_u.mutation.ResetCreditRate()
	_u.mutation.SetCreditRate(v)
	return _u
}

// SetNillableCreditRate sets the "credit_rate" field if the given value is not nil.
func (_u *ResellerPlanUpdateOne) SetNillableCreditRate(v *float64) *ResellerPlanUpdateOne {
	if v != nil {
		_u.SetCreditRate(*v)
	}
	return _u
}

// AddCreditRate adds value to the "credit_rate" field.
func (_u *ResellerPlanUpdateOne) AddCreditRate(v float64) *ResellerPlanUpdateOne {
	_u.mutation.AddCreditRate(v)
	return _u
}

// SetConcurrencyBonus sets the "concurrency_bonus" field.
func (_u *ResellerPlanUpdateOne) SetConcurrencyBonus(v int) *ResellerPlanUpdateOne {
	_u.mutation.ResetConcurrencyBonus()
	_u.mutation.SetConcurrencyBonus(v)
	return _u
}

// SetNillableConcurrencyBonus sets the "concurrency_bonus" field if the given value is not nil.
func (_u *ResellerPlanUpdateOne) SetNillableConcurrencyBonus(v *int) *ResellerPlanUpdateOne {
	if v != nil {
		_u.SetConcurrencyBonus(*v)
	}
	return _u
}

// AddConcurrencyBonus adds value to the "concurrency_bonus" field.
func (_u *ResellerPlanUpdateOne) AddConcurrencyBonus(v int) *ResellerPlanUpdateOne {
	_u.mutation.AddConcurrencyBonus(v)
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *ResellerPlanUpdateOne) SetRpmLimit(v int) *ResellerPlanUpdateOne {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *ResellerPlanUpdateOne) SetNillableRpmLimit(v *int) *ResellerPlanUpdateOne {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *ResellerPlanUpdateOne) AddRpmLimit(v int) *ResellerPlanUpdateOne {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetMaxDomains sets the "max_domains" field.
func (_u *ResellerPlanUpdateOne) SetMaxDomains(v int) *ResellerPlanUpdateOne {
	_u.mutation.ResetMaxDomains()
	_u.mutation.SetMaxDomains(v)
	return _u
}

// SetNillableMaxDomains sets the "max_domains" field if the given value is not nil.
func (_u *ResellerPlanUpdateOne) SetNillableMaxDomains(v *int) *ResellerPlanUpdateOne {
	if v != nil {
		_u.SetMaxDomains(*v)
	}
	return _u
}

// AddMaxDomains adds value to the "max_domains" field.
func (_u *ResellerPlanUpdateOne) AddMaxDomains(v int) *ResellerPlanUpdateOne {
	_u.mutation.AddMaxDomains(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *ResellerPlanUpdateOne) SetValidityDays(v int) *ResellerPlanUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *ResellerPlanUpdateOne) SetNillableValidityDays(v *int) *ResellerPlanUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *ResellerPlanUpdateOne) AddValidityDays(v int) *ResellerPlanUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (_u *ResellerPlanUpdateOne) SetAllowedGroupIds(v []int64) *ResellerPlanUpdateOne {
	_u.mutation.SetAllowedGroupIds(v)
	return _u
}

// AppendAllowedGroupIds appends value to the "allowed_group_ids" field.
func (_u *ResellerPlanUpdateOne) AppendAllowedGroupIds(v []int64) *ResellerPlanUpdateOne {
	_u.mutation.AppendAllowedGroupIds(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ResellerPlanUpdateOne) SetEnabled(v bool) *ResellerPlanUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ResellerPlanUpdateOne) SetNillableEnabled(v *bool) *ResellerPlanUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ResellerPlanMutation object of the builder.
func (_u *ResellerPlanUpdateOne) Mutation() *ResellerPlanMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResellerPlanUpdate builder.
func (_u *ResellerPlanUpdateOne) Where(ps ...predicate.ResellerPlan) *ResellerPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResellerPlanUpdateOne) Select(field string, fields ...string) *ResellerPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResellerPlan entity.
func (_u *ResellerPlanUpdateOne) Save(ctx context.Context) (*ResellerPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResellerPlanUpdateOne) SaveX(ctx context.Context) *ResellerPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResellerPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResellerPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResellerPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resellerplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResellerPlanUpdateOne) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := resellerplan.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := resellerplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConcurrencyBonus(); ok {
		if err := resellerplan.ConcurrencyBonusValidator(v); err != nil {
			return &ValidationError{Name: "concurrency_bonus", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.concurrency_bonus": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RpmLimit(); ok {
		if err := resellerplan.RpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "rpm_limit", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.rpm_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxDomains(); ok {
		if err := resellerplan.MaxDomainsValidator(v); err != nil {
			return &ValidationError{Name: "max_domains", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.max_domains": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidityDays(); ok {
		if err := resellerplan.ValidityDaysValidator(v); err != nil {
			return &ValidationError{Name: "validity_days", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.validity_days": %w`, err)}
		}
	}
	return nil
}

func (_u *ResellerPlanUpdateOne) sqlSave(ctx context.Context) (_node *ResellerPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resellerplan.Table, resellerplan.Columns, sqlgraph.NewFieldSpec(resellerplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResellerPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resellerplan.FieldID)
		for _, f := range fields {
			if !resellerplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resellerplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(resellerplan.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(resellerplan.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resellerplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(resellerplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(resellerplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditRate(); ok {
		_spec.SetField(resellerplan.FieldCreditRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditRate(); ok {
		_spec.AddField(resellerplan.FieldCreditRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ConcurrencyBonus(); ok {
		_spec.SetField(resellerplan.FieldConcurrencyBonus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrencyBonus(); ok {
		_spec.AddField(resellerplan.FieldConcurrencyBonus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(resellerplan.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(resellerplan.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxDomains(); ok {
		_spec.SetField(resellerplan.FieldMaxDomains, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxDomains(); ok {
		_spec.AddField(resellerplan.FieldMaxDomains, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(resellerplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(resellerplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AllowedGroupIds(); ok {
		_spec.SetField(resellerplan.FieldAllowedGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, resellerplan.FieldAllowedGroupIds, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(resellerplan.FieldEnabled, field.TypeBool, value)
	}
	_node = &ResellerPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resellerplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
