// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/resellerplan"
)

// ResellerPlanCreate is the builder for creating a ResellerPlan entity.
type ResellerPlanCreate struct {
	config
	mutation *ResellerPlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResellerPlanCreate) SetCreatedAt(v time.Time) *ResellerPlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResellerPlanCreate) SetNillableCreatedAt(v *time.Time) *ResellerPlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResellerPlanCreate) SetUpdatedAt(v time.Time) *ResellerPlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResellerPlanCreate) SetNillableUpdatedAt(v *time.Time) *ResellerPlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLevel sets the "level" field.
func (_c *ResellerPlanCreate) SetLevel(v int) *ResellerPlanCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ResellerPlanCreate) SetName(v string) *ResellerPlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *ResellerPlanCreate) SetPrice(v float64) *ResellerPlanCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetCreditRate sets the "credit_rate" field.
func (_c *ResellerPlanCreate) SetCreditRate(v float64) *ResellerPlanCreate {
	_c.mutation.SetCreditRate(v)
	return _c
}

// SetNillableCreditRate sets the "credit_rate" field if the given value is not nil.
func (_c *ResellerPlanCreate) SetNillableCreditRate(v *float64) *ResellerPlanCreate {
	if v != nil {
		_c.SetCreditRate(*v)
	}
	return _c
}

// SetConcurrencyBonus sets the "concurrency_bonus" field.
func (_c *ResellerPlanCreate) SetConcurrencyBonus(v int) *ResellerPlanCreate {
	_c.mutation.SetConcurrencyBonus(v)
	return _c
}

// SetNillableConcurrencyBonus sets the "concurrency_bonus" field if the given value is not nil.
func (_c *ResellerPlanCreate) SetNillableConcurrencyBonus(v *int) *ResellerPlanCreate {
	if v != nil {
		_c.SetConcurrencyBonus(*v)
	}
	return _c
}

// SetRpmLimit sets the "rpm_limit" field.
func (_c *ResellerPlanCreate) SetRpmLimit(v int) *ResellerPlanCreate {
	_c.mutation.SetRpmLimit(v)
	return _c
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_c *ResellerPlanCreate) SetNillableRpmLimit(v *int) *ResellerPlanCreate {
	if v != nil {
		_c.SetRpmLimit(*v)
	}
	return _c
}

// SetMaxDomains sets the "max_domains" field.
func (_c *ResellerPlanCreate) SetMaxDomains(v int) *ResellerPlanCreate {
	_c.mutation.SetMaxDomains(v)
	return _c
}

// SetNillableMaxDomains sets the "max_domains" field if the given value is not nil.
func (_c *ResellerPlanCreate) SetNillableMaxDomains(v *int) *ResellerPlanCreate {
	if v != nil {
		_c.SetMaxDomains(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *ResellerPlanCreate) SetValidityDays(v int) *ResellerPlanCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *ResellerPlanCreate) SetNillableValidityDays(v *int) *ResellerPlanCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (_c *ResellerPlanCreate) SetAllowedGroupIds(v []int64) *ResellerPlanCreate {
	_c.mutation.SetAllowedGroupIds(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ResellerPlanCreate) SetEnabled(v bool) *ResellerPlanCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ResellerPlanCreate) SetNillableEnabled(v *bool) *ResellerPlanCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// Mutation returns the ResellerPlanMutation object of the builder.
func (_c *ResellerPlanCreate) Mutation() *ResellerPlanMutation {
	return _c.mutation
}

// Save creates the ResellerPlan in the database.
func (_c *ResellerPlanCreate) Save(ctx context.Context) (*ResellerPlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResellerPlanCreate) SaveX(ctx context.Context) *ResellerPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResellerPlanCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resellerplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resellerplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreditRate(); !ok {
		v := resellerplan.DefaultCreditRate
		_c.mutation.SetCreditRate(v)
	}
	if _, ok := _c.mutation.ConcurrencyBonus(); !ok {
		v := resellerplan.DefaultConcurrencyBonus
		_c.mutation.SetConcurrencyBonus(v)
	}
	if _, ok := _c.mutation.RpmLimit(); !ok {
		v := resellerplan.DefaultRpmLimit
		_c.mutation.SetRpmLimit(v)
	}
	if _, ok := _c.mutation.MaxDomains(); !ok {
		v := resellerplan.DefaultMaxDomains
		_c.mutation.SetMaxDomains(v)
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := resellerplan.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
	if _, ok := _c.mutation.AllowedGroupIds(); !ok {
		v := resellerplan.DefaultAllowedGroupIds
		_c.mutation.SetAllowedGroupIds(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := resellerplan.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResellerPlanCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResellerPlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResellerPlan.updated_at"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "ResellerPlan.level"`)}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := resellerplan.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ResellerPlan.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := resellerplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ResellerPlan.price"`)}
	}
	if _, ok := _c.mutation.CreditRate(); !ok {
		return &ValidationError{Name: "credit_rate", err: errors.New(`ent: missing required field "ResellerPlan.credit_rate"`)}
	}
	if _, ok := _c.mutation.ConcurrencyBonus(); !ok {
		return &ValidationError{Name: "concurrency_bonus", err: errors.New(`ent: missing required field "ResellerPlan.concurrency_bonus"`)}
	}
	if v, ok := _c.mutation.ConcurrencyBonus(); ok {
		if err := resellerplan.ConcurrencyBonusValidator(v); err != nil {
			return &ValidationError{Name: "concurrency_bonus", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.concurrency_bonus": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RpmLimit(); !ok {
		return &ValidationError{Name: "rpm_limit", err: errors.New(`ent: missing required field "ResellerPlan.rpm_limit"`)}
	}
	if v, ok := _c.mutation.RpmLimit(); ok {
		if err := resellerplan.RpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "rpm_limit", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.rpm_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxDomains(); !ok {
		return &ValidationError{Name: "max_domains", err: errors.New(`ent: missing required field "ResellerPlan.max_domains"`)}
	}
	if v, ok := _c.mutation.MaxDomains(); ok {
		if err := resellerplan.MaxDomainsValidator(v); err != nil {
			return &ValidationError{Name: "max_domains", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.max_domains": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "ResellerPlan.validity_days"`)}
	}
	if v, ok := _c.mutation.ValidityDays(); ok {
		if err := resellerplan.ValidityDaysValidator(v); err != nil {
			return &ValidationError{Name: "validity_days", err: fmt.Errorf(`ent: validator failed for field "ResellerPlan.validity_days": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AllowedGroupIds(); !ok {
		return &ValidationError{Name: "allowed_group_ids", err: errors.New(`ent: missing required field "ResellerPlan.allowed_group_ids"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ResellerPlan.enabled"`)}
	}
	return nil
}

func (_c *ResellerPlanCreate) sqlSave(ctx context.Context) (*ResellerPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResellerPlanCreate) createSpec() (*ResellerPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &ResellerPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resellerplan.Table, sqlgraph.NewFieldSpec(resellerplan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resellerplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(resellerplan.FieldLevel, field.TypeInt, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(resellerplan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(resellerplan.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.CreditRate(); ok {
		_spec.SetField(resellerplan.FieldCreditRate, field.TypeFloat64, value)
		_node.CreditRate = value
	}
	if value, ok := _c.mutation.ConcurrencyBonus(); ok {
		_spec.SetField(resellerplan.FieldConcurrencyBonus, field.TypeInt, value)
		_node.ConcurrencyBonus = value
	}
	if value, ok := _c.mutation.RpmLimit(); ok {
		_spec.SetField(resellerplan.FieldRpmLimit, field.TypeInt, value)
		_node.RpmLimit = value
	}
	if value, ok := _c.mutation.MaxDomains(); ok {
		_spec.SetField(resellerplan.FieldMaxDomains, field.TypeInt, value)
		_node.MaxDomains = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(resellerplan.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.AllowedGroupIds(); ok {
		_spec.SetField(resellerplan.FieldAllowedGroupIds, field.TypeJSON, value)
		_node.AllowedGroupIds = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(resellerplan.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerPlan.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerPlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerPlanCreate) OnConflict(opts ...sql.ConflictOption) *ResellerPlanUpsertOne {
	_c.conflict = opts
	return &ResellerPlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerPlanCreate) OnConflictColumns(columns ...string) *ResellerPlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerPlanUpsertOne{
		create: _c,
	}
}

type (
	// ResellerPlanUpsertOne is the builder for "upsert"-ing
	//  one ResellerPlan node.
	ResellerPlanUpsertOne struct {
		create *ResellerPlanCreate
	}

	// ResellerPlanUpsert is the "OnConflict" setter.
	ResellerPlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerPlanUpsert) SetUpdatedAt(v time.Time) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateUpdatedAt() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldUpdatedAt)
	return u
}

// SetLevel sets the "level" field.
func (u *ResellerPlanUpsert) SetLevel(v int) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldLevel, v)
	return u
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateLevel() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldLevel)
	return u
}

// AddLevel adds v to the "level" field.
func (u *ResellerPlanUpsert) AddLevel(v int) *ResellerPlanUpsert {
	u.Add(resellerplan.FieldLevel, v)
	return u
}

// SetName sets the "name" field.
func (u *ResellerPlanUpsert) SetName(v string) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateName() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldName)
	return u
}

// SetPrice sets the "price" field.
func (u *ResellerPlanUpsert) SetPrice(v float64) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdatePrice() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *ResellerPlanUpsert) AddPrice(v float64) *ResellerPlanUpsert {
	u.Add(resellerplan.FieldPrice, v)
	return u
}

// SetCreditRate sets the "credit_rate" field.
func (u *ResellerPlanUpsert) SetCreditRate(v float64) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldCreditRate, v)
	return u
}

// UpdateCreditRate sets the "credit_rate" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateCreditRate() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldCreditRate)
	return u
}

// AddCreditRate adds v to the "credit_rate" field.
func (u *ResellerPlanUpsert) AddCreditRate(v float64) *ResellerPlanUpsert {
	u.Add(resellerplan.FieldCreditRate, v)
	return u
}

// SetConcurrencyBonus sets the "concurrency_bonus" field.
func (u *ResellerPlanUpsert) SetConcurrencyBonus(v int) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldConcurrencyBonus, v)
	return u
}

// UpdateConcurrencyBonus sets the "concurrency_bonus" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateConcurrencyBonus() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldConcurrencyBonus)
	return u
}

// AddConcurrencyBonus adds v to the "concurrency_bonus" field.
func (u *ResellerPlanUpsert) AddConcurrencyBonus(v int) *ResellerPlanUpsert {
	u.Add(resellerplan.FieldConcurrencyBonus, v)
	return u
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *ResellerPlanUpsert) SetRpmLimit(v int) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldRpmLimit, v)
	return u
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateRpmLimit() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldRpmLimit)
	return u
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *ResellerPlanUpsert) AddRpmLimit(v int) *ResellerPlanUpsert {
	u.Add(resellerplan.FieldRpmLimit, v)
	return u
}

// SetMaxDomains sets the "max_domains" field.
func (u *ResellerPlanUpsert) SetMaxDomains(v int) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldMaxDomains, v)
	return u
}

// UpdateMaxDomains sets the "max_domains" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateMaxDomains() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldMaxDomains)
	return u
}

// AddMaxDomains adds v to the "max_domains" field.
func (u *ResellerPlanUpsert) AddMaxDomains(v int) *ResellerPlanUpsert {
	u.Add(resellerplan.FieldMaxDomains, v)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *ResellerPlanUpsert) SetValidityDays(v int) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateValidityDays() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *ResellerPlanUpsert) AddValidityDays(v int) *ResellerPlanUpsert {
	u.Add(resellerplan.FieldValidityDays, v)
	return u
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (u *ResellerPlanUpsert) SetAllowedGroupIds(v []int64) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldAllowedGroupIds, v)
	return u
}

// UpdateAllowedGroupIds sets the "allowed_group_ids" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateAllowedGroupIds() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldAllowedGroupIds)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ResellerPlanUpsert) SetEnabled(v bool) *ResellerPlanUpsert {
	u.Set(resellerplan.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ResellerPlanUpsert) UpdateEnabled() *ResellerPlanUpsert {
	u.SetExcluded(resellerplan.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResellerPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResellerPlanUpsertOne) UpdateNewValues() *ResellerPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resellerplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerPlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResellerPlanUpsertOne) Ignore() *ResellerPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerPlanUpsertOne) DoNothing() *ResellerPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerPlanCreate.OnConflict
// documentation for more info.
func (u *ResellerPlanUpsertOne) Update(set func(*ResellerPlanUpsert)) *ResellerPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerPlanUpsertOne) SetUpdatedAt(v time.Time) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateUpdatedAt() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLevel sets the "level" field.
func (u *ResellerPlanUpsertOne) SetLevel(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetLevel(v)
	})
}

// AddLevel adds v to the "level" field.
func (u *ResellerPlanUpsertOne) AddLevel(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateLevel() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateLevel()
	})
}

// SetName sets the "name" field.
func (u *ResellerPlanUpsertOne) SetName(v string) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateName() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateName()
	})
}

// SetPrice sets the "price" field.
func (u *ResellerPlanUpsertOne) SetPrice(v float64) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ResellerPlanUpsertOne) AddPrice(v float64) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdatePrice() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdatePrice()
	})
}

// SetCreditRate sets the "credit_rate" field.
func (u *ResellerPlanUpsertOne) SetCreditRate(v float64) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetCreditRate(v)
	})
}

// AddCreditRate adds v to the "credit_rate" field.
func (u *ResellerPlanUpsertOne) AddCreditRate(v float64) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddCreditRate(v)
	})
}

// UpdateCreditRate sets the "credit_rate" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateCreditRate() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateCreditRate()
	})
}

// SetConcurrencyBonus sets the "concurrency_bonus" field.
func (u *ResellerPlanUpsertOne) SetConcurrencyBonus(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetConcurrencyBonus(v)
	})
}

// AddConcurrencyBonus adds v to the "concurrency_bonus" field.
func (u *ResellerPlanUpsertOne) AddConcurrencyBonus(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddConcurrencyBonus(v)
	})
}

// UpdateConcurrencyBonus sets the "concurrency_bonus" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateConcurrencyBonus() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateConcurrencyBonus()
	})
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *ResellerPlanUpsertOne) SetRpmLimit(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetRpmLimit(v)
	})
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *ResellerPlanUpsertOne) AddRpmLimit(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddRpmLimit(v)
	})
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateRpmLimit() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateRpmLimit()
	})
}

// SetMaxDomains sets the "max_domains" field.
func (u *ResellerPlanUpsertOne) SetMaxDomains(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetMaxDomains(v)
	})
}

// AddMaxDomains adds v to the "max_domains" field.
func (u *ResellerPlanUpsertOne) AddMaxDomains(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddMaxDomains(v)
	})
}

// UpdateMaxDomains sets the "max_domains" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateMaxDomains() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateMaxDomains()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *ResellerPlanUpsertOne) SetValidityDays(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *ResellerPlanUpsertOne) AddValidityDays(v int) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateValidityDays() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (u *ResellerPlanUpsertOne) SetAllowedGroupIds(v []int64) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetAllowedGroupIds(v)
	})
}

// UpdateAllowedGroupIds sets the "allowed_group_ids" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateAllowedGroupIds() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateAllowedGroupIds()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ResellerPlanUpsertOne) SetEnabled(v bool) *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ResellerPlanUpsertOne) UpdateEnabled() *ResellerPlanUpsertOne {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *ResellerPlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerPlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerPlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResellerPlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResellerPlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResellerPlanCreateBulk is the builder for creating many ResellerPlan entities in bulk.
type ResellerPlanCreateBulk struct {
	config
	err      error
	builders []*ResellerPlanCreate
	conflict []sql.ConflictOption
}

// Save creates the ResellerPlan entities in the database.
func (_c *ResellerPlanCreateBulk) Save(ctx context.Context) ([]*ResellerPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResellerPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResellerPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResellerPlanCreateBulk) SaveX(ctx context.Context) []*ResellerPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerPlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerPlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerPlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResellerPlanUpsertBulk {
	_c.conflict = opts
	return &ResellerPlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerPlanCreateBulk) OnConflictColumns(columns ...string) *ResellerPlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerPlanUpsertBulk{
		create: _c,
	}
}

// ResellerPlanUpsertBulk is the builder for "upsert"-ing
// a bulk of ResellerPlan nodes.
type ResellerPlanUpsertBulk struct {
	create *ResellerPlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResellerPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResellerPlanUpsertBulk) UpdateNewValues() *ResellerPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resellerplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerPlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResellerPlanUpsertBulk) Ignore() *ResellerPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerPlanUpsertBulk) DoNothing() *ResellerPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerPlanCreateBulk.OnConflict
// documentation for more info.
func (u *ResellerPlanUpsertBulk) Update(set func(*ResellerPlanUpsert)) *ResellerPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerPlanUpsertBulk) SetUpdatedAt(v time.Time) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateUpdatedAt() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLevel sets the "level" field.
func (u *ResellerPlanUpsertBulk) SetLevel(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetLevel(v)
	})
}

// AddLevel adds v to the "level" field.
func (u *ResellerPlanUpsertBulk) AddLevel(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateLevel() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateLevel()
	})
}

// SetName sets the "name" field.
func (u *ResellerPlanUpsertBulk) SetName(v string) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateName() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateName()
	})
}

// SetPrice sets the "price" field.
func (u *ResellerPlanUpsertBulk) SetPrice(v float64) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *ResellerPlanUpsertBulk) AddPrice(v float64) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdatePrice() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdatePrice()
	})
}

// SetCreditRate sets the "credit_rate" field.
func (u *ResellerPlanUpsertBulk) SetCreditRate(v float64) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetCreditRate(v)
	})
}

// AddCreditRate adds v to the "credit_rate" field.
func (u *ResellerPlanUpsertBulk) AddCreditRate(v float64) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddCreditRate(v)
	})
}

// UpdateCreditRate sets the "credit_rate" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateCreditRate() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateCreditRate()
	})
}

// SetConcurrencyBonus sets the "concurrency_bonus" field.
func (u *ResellerPlanUpsertBulk) SetConcurrencyBonus(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetConcurrencyBonus(v)
	})
}

// AddConcurrencyBonus adds v to the "concurrency_bonus" field.
func (u *ResellerPlanUpsertBulk) AddConcurrencyBonus(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddConcurrencyBonus(v)
	})
}

// UpdateConcurrencyBonus sets the "concurrency_bonus" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateConcurrencyBonus() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateConcurrencyBonus()
	})
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *ResellerPlanUpsertBulk) SetRpmLimit(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetRpmLimit(v)
	})
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *ResellerPlanUpsertBulk) AddRpmLimit(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddRpmLimit(v)
	})
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateRpmLimit() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateRpmLimit()
	})
}

// SetMaxDomains sets the "max_domains" field.
func (u *ResellerPlanUpsertBulk) SetMaxDomains(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetMaxDomains(v)
	})
}

// AddMaxDomains adds v to the "max_domains" field.
func (u *ResellerPlanUpsertBulk) AddMaxDomains(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddMaxDomains(v)
	})
}

// UpdateMaxDomains sets the "max_domains" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateMaxDomains() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateMaxDomains()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *ResellerPlanUpsertBulk) SetValidityDays(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *ResellerPlanUpsertBulk) AddValidityDays(v int) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateValidityDays() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetAllowedGroupIds sets the "allowed_group_ids" field.
func (u *ResellerPlanUpsertBulk) SetAllowedGroupIds(v []int64) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetAllowedGroupIds(v)
	})
}

// UpdateAllowedGroupIds sets the "allowed_group_ids" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateAllowedGroupIds() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateAllowedGroupIds()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ResellerPlanUpsertBulk) SetEnabled(v bool) *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ResellerPlanUpsertBulk) UpdateEnabled() *ResellerPlanUpsertBulk {
	return u.Update(func(s *ResellerPlanUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *ResellerPlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResellerPlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerPlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerPlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
