// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/resellerplan"
)

// ResellerPlan is the model entity for the ResellerPlan schema.
type ResellerPlan struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Level holds the value of the "level" field.
	Level int `json:"level,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// CreditRate holds the value of the "credit_rate" field.
	CreditRate float64 `json:"credit_rate,omitempty"`
	// ConcurrencyBonus holds the value of the "concurrency_bonus" field.
	ConcurrencyBonus int `json:"concurrency_bonus,omitempty"`
	// RpmLimit holds the value of the "rpm_limit" field.
	RpmLimit int `json:"rpm_limit,omitempty"`
	// MaxDomains holds the value of the "max_domains" field.
	MaxDomains int `json:"max_domains,omitempty"`
	// ValidityDays holds the value of the "validity_days" field.
	ValidityDays int `json:"validity_days,omitempty"`
	// AllowedGroupIds holds the value of the "allowed_group_ids" field.
	AllowedGroupIds []int64 `json:"allowed_group_ids,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResellerPlan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resellerplan.FieldAllowedGroupIds:
			values[i] = new([]byte)
		case resellerplan.FieldEnabled:
			values[i] = new(sql.NullBool)
		case resellerplan.FieldPrice, resellerplan.FieldCreditRate:
			values[i] = new(sql.NullFloat64)
		case resellerplan.FieldID, resellerplan.FieldLevel, resellerplan.FieldConcurrencyBonus, resellerplan.FieldRpmLimit, resellerplan.FieldMaxDomains, resellerplan.FieldValidityDays:
			values[i] = new(sql.NullInt64)
		case resellerplan.FieldName:
			values[i] = new(sql.NullString)
		case resellerplan.FieldCreatedAt, resellerplan.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResellerPlan fields.
func (_m *ResellerPlan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resellerplan.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case resellerplan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resellerplan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case resellerplan.FieldLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = int(value.Int64)
			}
		case resellerplan.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case resellerplan.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case resellerplan.FieldCreditRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_rate", values[i])
			} else if value.Valid {
				_m.CreditRate = value.Float64
			}
		case resellerplan.FieldConcurrencyBonus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency_bonus", values[i])
			} else if value.Valid {
				_m.ConcurrencyBonus = int(value.Int64)
			}
		case resellerplan.FieldRpmLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rpm_limit", values[i])
			} else if value.Valid {
				_m.RpmLimit = int(value.Int64)
			}
		case resellerplan.FieldMaxDomains:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_domains", values[i])
			} else if value.Valid {
				_m.MaxDomains = int(value.Int64)
			}
		case resellerplan.FieldValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days", values[i])
			} else if value.Valid {
				_m.ValidityDays = int(value.Int64)
			}
		case resellerplan.FieldAllowedGroupIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_group_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedGroupIds); err != nil {
					return fmt.Errorf("unmarshal field allowed_group_ids: %w", err)
				}
			}
		case resellerplan.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResellerPlan.
// This includes values selected through modifiers, order, etc.
func (_m *ResellerPlan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ResellerPlan.
// Note that you need to call ResellerPlan.Unwrap() before calling this method if this ResellerPlan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResellerPlan) Update() *ResellerPlanUpdateOne {
	return NewResellerPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResellerPlan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResellerPlan) Unwrap() *ResellerPlan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResellerPlan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResellerPlan) String() string {
	var builder strings.Builder
	builder.WriteString("ResellerPlan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("credit_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditRate))
	builder.WriteString(", ")
	builder.WriteString("concurrency_bonus=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConcurrencyBonus))
	builder.WriteString(", ")
	builder.WriteString("rpm_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.RpmLimit))
	builder.WriteString(", ")
	builder.WriteString("max_domains=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxDomains))
	builder.WriteString(", ")
	builder.WriteString("validity_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidityDays))
	builder.WriteString(", ")
	builder.WriteString("allowed_group_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedGroupIds))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// ResellerPlans is a parsable slice of ResellerPlan.
type ResellerPlans []*ResellerPlan
