// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/resellerdomain"
)

// ResellerDomain is the model entity for the ResellerDomain schema.
type ResellerDomain struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain string `json:"domain,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// SiteName holds the value of the "site_name" field.
	SiteName string `json:"site_name,omitempty"`
	// SiteLogo holds the value of the "site_logo" field.
	SiteLogo string `json:"site_logo,omitempty"`
	// SiteSubtitle holds the value of the "site_subtitle" field.
	SiteSubtitle string `json:"site_subtitle,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResellerDomain) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resellerdomain.FieldID, resellerdomain.FieldUserID:
			values[i] = new(sql.NullInt64)
		case resellerdomain.FieldDomain, resellerdomain.FieldStatus, resellerdomain.FieldNotes, resellerdomain.FieldSiteName, resellerdomain.FieldSiteLogo, resellerdomain.FieldSiteSubtitle:
			values[i] = new(sql.NullString)
		case resellerdomain.FieldCreatedAt, resellerdomain.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResellerDomain fields.
func (_m *ResellerDomain) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resellerdomain.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case resellerdomain.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resellerdomain.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case resellerdomain.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				_m.Domain = value.String
			}
		case resellerdomain.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case resellerdomain.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case resellerdomain.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case resellerdomain.FieldSiteName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_name", values[i])
			} else if value.Valid {
				_m.SiteName = value.String
			}
		case resellerdomain.FieldSiteLogo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_logo", values[i])
			} else if value.Valid {
				_m.SiteLogo = value.String
			}
		case resellerdomain.FieldSiteSubtitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_subtitle", values[i])
			} else if value.Valid {
				_m.SiteSubtitle = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResellerDomain.
// This includes values selected through modifiers, order, etc.
func (_m *ResellerDomain) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ResellerDomain.
// Note that you need to call ResellerDomain.Unwrap() before calling this method if this ResellerDomain
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResellerDomain) Update() *ResellerDomainUpdateOne {
	return NewResellerDomainClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResellerDomain entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResellerDomain) Unwrap() *ResellerDomain {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResellerDomain is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResellerDomain) String() string {
	var builder strings.Builder
	builder.WriteString("ResellerDomain(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("domain=")
	builder.WriteString(_m.Domain)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("site_name=")
	builder.WriteString(_m.SiteName)
	builder.WriteString(", ")
	builder.WriteString("site_logo=")
	builder.WriteString(_m.SiteLogo)
	builder.WriteString(", ")
	builder.WriteString("site_subtitle=")
	builder.WriteString(_m.SiteSubtitle)
	builder.WriteByte(')')
	return builder.String()
}

// ResellerDomains is a parsable slice of ResellerDomain.
type ResellerDomains []*ResellerDomain
