// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/resellerdomain"
)

// ResellerDomainCreate is the builder for creating a ResellerDomain entity.
type ResellerDomainCreate struct {
	config
	mutation *ResellerDomainMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResellerDomainCreate) SetCreatedAt(v time.Time) *ResellerDomainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableCreatedAt(v *time.Time) *ResellerDomainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResellerDomainCreate) SetUpdatedAt(v time.Time) *ResellerDomainCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableUpdatedAt(v *time.Time) *ResellerDomainCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDomain sets the "domain" field.
func (_c *ResellerDomainCreate) SetDomain(v string) *ResellerDomainCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ResellerDomainCreate) SetUserID(v int64) *ResellerDomainCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResellerDomainCreate) SetStatus(v string) *ResellerDomainCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableStatus(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ResellerDomainCreate) SetNotes(v string) *ResellerDomainCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ResellerDomainCreate) SetNillableNotes(v *string) *ResellerDomainCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// Mutation returns the ResellerDomainMutation object of the builder.
func (_c *ResellerDomainCreate) Mutation() *ResellerDomainMutation {
	return _c.mutation
}

// Save creates the ResellerDomain in the database.
func (_c *ResellerDomainCreate) Save(ctx context.Context) (*ResellerDomain, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResellerDomainCreate) SaveX(ctx context.Context) *ResellerDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerDomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerDomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResellerDomainCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resellerdomain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resellerdomain.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := resellerdomain.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := resellerdomain.DefaultNotes
		_c.mutation.SetNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResellerDomainCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResellerDomain.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResellerDomain.updated_at"`)}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "ResellerDomain.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := resellerdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ResellerDomain.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ResellerDomain.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := resellerdomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResellerDomain.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "ResellerDomain.notes"`)}
	}
	return nil
}

func (_c *ResellerDomainCreate) sqlSave(ctx context.Context) (*ResellerDomain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResellerDomainCreate) createSpec() (*ResellerDomain, *sqlgraph.CreateSpec) {
	var (
		_node = &ResellerDomain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resellerdomain.Table, sqlgraph.NewFieldSpec(resellerdomain.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resellerdomain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resellerdomain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(resellerdomain.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(resellerdomain.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(resellerdomain.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(resellerdomain.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerDomain.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerDomainUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerDomainCreate) OnConflict(opts ...sql.ConflictOption) *ResellerDomainUpsertOne {
	_c.conflict = opts
	return &ResellerDomainUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerDomainCreate) OnConflictColumns(columns ...string) *ResellerDomainUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerDomainUpsertOne{
		create: _c,
	}
}

type (
	// ResellerDomainUpsertOne is the builder for "upsert"-ing
	//  one ResellerDomain node.
	ResellerDomainUpsertOne struct {
		create *ResellerDomainCreate
	}

	// ResellerDomainUpsert is the "OnConflict" setter.
	ResellerDomainUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerDomainUpsert) SetUpdatedAt(v time.Time) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateUpdatedAt() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldUpdatedAt)
	return u
}

// SetDomain sets the "domain" field.
func (u *ResellerDomainUpsert) SetDomain(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldDomain, v)
	return u
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateDomain() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldDomain)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ResellerDomainUpsert) SetUserID(v int64) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateUserID() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ResellerDomainUpsert) AddUserID(v int64) *ResellerDomainUpsert {
	u.Add(resellerdomain.FieldUserID, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ResellerDomainUpsert) SetStatus(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateStatus() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldStatus)
	return u
}

// SetNotes sets the "notes" field.
func (u *ResellerDomainUpsert) SetNotes(v string) *ResellerDomainUpsert {
	u.Set(resellerdomain.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ResellerDomainUpsert) UpdateNotes() *ResellerDomainUpsert {
	u.SetExcluded(resellerdomain.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResellerDomainUpsertOne) UpdateNewValues() *ResellerDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resellerdomain.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResellerDomainUpsertOne) Ignore() *ResellerDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerDomainUpsertOne) DoNothing() *ResellerDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerDomainCreate.OnConflict
// documentation for more info.
func (u *ResellerDomainUpsertOne) Update(set func(*ResellerDomainUpsert)) *ResellerDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerDomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerDomainUpsertOne) SetUpdatedAt(v time.Time) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateUpdatedAt() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDomain sets the "domain" field.
func (u *ResellerDomainUpsertOne) SetDomain(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateDomain() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDomain()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResellerDomainUpsertOne) SetUserID(v int64) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResellerDomainUpsertOne) AddUserID(v int64) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateUserID() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateUserID()
	})
}

// SetStatus sets the "status" field.
func (u *ResellerDomainUpsertOne) SetStatus(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateStatus() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *ResellerDomainUpsertOne) SetNotes(v string) *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ResellerDomainUpsertOne) UpdateNotes() *ResellerDomainUpsertOne {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *ResellerDomainUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerDomainCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerDomainUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResellerDomainUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResellerDomainUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResellerDomainCreateBulk is the builder for creating many ResellerDomain entities in bulk.
type ResellerDomainCreateBulk struct {
	config
	err      error
	builders []*ResellerDomainCreate
	conflict []sql.ConflictOption
}

// Save creates the ResellerDomain entities in the database.
func (_c *ResellerDomainCreateBulk) Save(ctx context.Context) ([]*ResellerDomain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResellerDomain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResellerDomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResellerDomainCreateBulk) SaveX(ctx context.Context) []*ResellerDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResellerDomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResellerDomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResellerDomain.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResellerDomainUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResellerDomainCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResellerDomainUpsertBulk {
	_c.conflict = opts
	return &ResellerDomainUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResellerDomainCreateBulk) OnConflictColumns(columns ...string) *ResellerDomainUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResellerDomainUpsertBulk{
		create: _c,
	}
}

// ResellerDomainUpsertBulk is the builder for "upsert"-ing
// a bulk of ResellerDomain nodes.
type ResellerDomainUpsertBulk struct {
	create *ResellerDomainCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResellerDomainUpsertBulk) UpdateNewValues() *ResellerDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resellerdomain.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResellerDomain.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResellerDomainUpsertBulk) Ignore() *ResellerDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResellerDomainUpsertBulk) DoNothing() *ResellerDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResellerDomainCreateBulk.OnConflict
// documentation for more info.
func (u *ResellerDomainUpsertBulk) Update(set func(*ResellerDomainUpsert)) *ResellerDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResellerDomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResellerDomainUpsertBulk) SetUpdatedAt(v time.Time) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateUpdatedAt() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDomain sets the "domain" field.
func (u *ResellerDomainUpsertBulk) SetDomain(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateDomain() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateDomain()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResellerDomainUpsertBulk) SetUserID(v int64) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResellerDomainUpsertBulk) AddUserID(v int64) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateUserID() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateUserID()
	})
}

// SetStatus sets the "status" field.
func (u *ResellerDomainUpsertBulk) SetStatus(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateStatus() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *ResellerDomainUpsertBulk) SetNotes(v string) *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ResellerDomainUpsertBulk) UpdateNotes() *ResellerDomainUpsertBulk {
	return u.Update(func(s *ResellerDomainUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *ResellerDomainUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResellerDomainCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResellerDomainCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResellerDomainUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
