// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/useraddon"
)

// UserAddonCreate is the builder for creating a UserAddon entity.
type UserAddonCreate struct {
	config
	mutation *UserAddonMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAddonCreate) SetCreatedAt(v time.Time) *UserAddonCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAddonCreate) SetNillableCreatedAt(v *time.Time) *UserAddonCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAddonCreate) SetUpdatedAt(v time.Time) *UserAddonCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAddonCreate) SetNillableUpdatedAt(v *time.Time) *UserAddonCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserAddonCreate) SetUserID(v int64) *UserAddonCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *UserAddonCreate) SetKind(v string) *UserAddonCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *UserAddonCreate) SetAmount(v int) *UserAddonCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *UserAddonCreate) SetNillableAmount(v *int) *UserAddonCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserAddonCreate) SetExpiresAt(v time.Time) *UserAddonCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the UserAddonMutation object of the builder.
func (_c *UserAddonCreate) Mutation() *UserAddonMutation {
	return _c.mutation
}

// Save creates the UserAddon in the database.
func (_c *UserAddonCreate) Save(ctx context.Context) (*UserAddon, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAddonCreate) SaveX(ctx context.Context) *UserAddon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAddonCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAddonCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAddonCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useraddon.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := useraddon.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := useraddon.DefaultAmount
		_c.mutation.SetAmount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAddonCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAddon.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAddon.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserAddon.user_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "UserAddon.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := useraddon.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "UserAddon.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "UserAddon.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := useraddon.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "UserAddon.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserAddon.expires_at"`)}
	}
	return nil
}

func (_c *UserAddonCreate) sqlSave(ctx context.Context) (*UserAddon, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAddonCreate) createSpec() (*UserAddon, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAddon{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useraddon.Table, sqlgraph.NewFieldSpec(useraddon.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useraddon.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useraddon.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(useraddon.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(useraddon.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(useraddon.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(useraddon.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAddon.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAddonUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAddonCreate) OnConflict(opts ...sql.ConflictOption) *UserAddonUpsertOne {
	_c.conflict = opts
	return &UserAddonUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAddon.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAddonCreate) OnConflictColumns(columns ...string) *UserAddonUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAddonUpsertOne{
		create: _c,
	}
}

type (
	// UserAddonUpsertOne is the builder for "upsert"-ing
	//  one UserAddon node.
	UserAddonUpsertOne struct {
		create *UserAddonCreate
	}

	// UserAddonUpsert is the "OnConflict" setter.
	UserAddonUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAddonUpsert) SetUpdatedAt(v time.Time) *UserAddonUpsert {
	u.Set(useraddon.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAddonUpsert) UpdateUpdatedAt() *UserAddonUpsert {
	u.SetExcluded(useraddon.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserAddonUpsert) SetUserID(v int64) *UserAddonUpsert {
	u.Set(useraddon.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAddonUpsert) UpdateUserID() *UserAddonUpsert {
	u.SetExcluded(useraddon.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserAddonUpsert) AddUserID(v int64) *UserAddonUpsert {
	u.Add(useraddon.FieldUserID, v)
	return u
}

// SetKind sets the "kind" field.
func (u *UserAddonUpsert) SetKind(v string) *UserAddonUpsert {
	u.Set(useraddon.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UserAddonUpsert) UpdateKind() *UserAddonUpsert {
	u.SetExcluded(useraddon.FieldKind)
	return u
}

// SetAmount sets the "amount" field.
func (u *UserAddonUpsert) SetAmount(v int) *UserAddonUpsert {
	u.Set(useraddon.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserAddonUpsert) UpdateAmount() *UserAddonUpsert {
	u.SetExcluded(useraddon.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *UserAddonUpsert) AddAmount(v int) *UserAddonUpsert {
	u.Add(useraddon.FieldAmount, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserAddonUpsert) SetExpiresAt(v time.Time) *UserAddonUpsert {
	u.Set(useraddon.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserAddonUpsert) UpdateExpiresAt() *UserAddonUpsert {
	u.SetExcluded(useraddon.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserAddon.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAddonUpsertOne) UpdateNewValues() *UserAddonUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(useraddon.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAddon.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserAddonUpsertOne) Ignore() *UserAddonUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAddonUpsertOne) DoNothing() *UserAddonUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAddonCreate.OnConflict
// documentation for more info.
func (u *UserAddonUpsertOne) Update(set func(*UserAddonUpsert)) *UserAddonUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAddonUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAddonUpsertOne) SetUpdatedAt(v time.Time) *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAddonUpsertOne) UpdateUpdatedAt() *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserAddonUpsertOne) SetUserID(v int64) *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserAddonUpsertOne) AddUserID(v int64) *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAddonUpsertOne) UpdateUserID() *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateUserID()
	})
}

// SetKind sets the "kind" field.
func (u *UserAddonUpsertOne) SetKind(v string) *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UserAddonUpsertOne) UpdateKind() *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateKind()
	})
}

// SetAmount sets the "amount" field.
func (u *UserAddonUpsertOne) SetAmount(v int) *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserAddonUpsertOne) AddAmount(v int) *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserAddonUpsertOne) UpdateAmount() *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateAmount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserAddonUpsertOne) SetExpiresAt(v time.Time) *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserAddonUpsertOne) UpdateExpiresAt() *UserAddonUpsertOne {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *UserAddonUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAddonCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAddonUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserAddonUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserAddonUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserAddonCreateBulk is the builder for creating many UserAddon entities in bulk.
type UserAddonCreateBulk struct {
	config
	err      error
	builders []*UserAddonCreate
	conflict []sql.ConflictOption
}

// Save creates the UserAddon entities in the database.
func (_c *UserAddonCreateBulk) Save(ctx context.Context) ([]*UserAddon, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAddon, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAddonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAddonCreateBulk) SaveX(ctx context.Context) []*UserAddon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAddonCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAddonCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAddon.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAddonUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAddonCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserAddonUpsertBulk {
	_c.conflict = opts
	return &UserAddonUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAddon.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAddonCreateBulk) OnConflictColumns(columns ...string) *UserAddonUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAddonUpsertBulk{
		create: _c,
	}
}

// UserAddonUpsertBulk is the builder for "upsert"-ing
// a bulk of UserAddon nodes.
type UserAddonUpsertBulk struct {
	create *UserAddonCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserAddon.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAddonUpsertBulk) UpdateNewValues() *UserAddonUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(useraddon.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAddon.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserAddonUpsertBulk) Ignore() *UserAddonUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAddonUpsertBulk) DoNothing() *UserAddonUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAddonCreateBulk.OnConflict
// documentation for more info.
func (u *UserAddonUpsertBulk) Update(set func(*UserAddonUpsert)) *UserAddonUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAddonUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAddonUpsertBulk) SetUpdatedAt(v time.Time) *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAddonUpsertBulk) UpdateUpdatedAt() *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserAddonUpsertBulk) SetUserID(v int64) *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserAddonUpsertBulk) AddUserID(v int64) *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAddonUpsertBulk) UpdateUserID() *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateUserID()
	})
}

// SetKind sets the "kind" field.
func (u *UserAddonUpsertBulk) SetKind(v string) *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UserAddonUpsertBulk) UpdateKind() *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateKind()
	})
}

// SetAmount sets the "amount" field.
func (u *UserAddonUpsertBulk) SetAmount(v int) *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserAddonUpsertBulk) AddAmount(v int) *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserAddonUpsertBulk) UpdateAmount() *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateAmount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserAddonUpsertBulk) SetExpiresAt(v time.Time) *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserAddonUpsertBulk) UpdateExpiresAt() *UserAddonUpsertBulk {
	return u.Update(func(s *UserAddonUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *UserAddonUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserAddonCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAddonCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAddonUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
