// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/useraddon"
)

// UserAddonUpdate is the builder for updating UserAddon entities.
type UserAddonUpdate struct {
	config
	hooks    []Hook
	mutation *UserAddonMutation
}

// Where appends a list predicates to the UserAddonUpdate builder.
func (_u *UserAddonUpdate) Where(ps ...predicate.UserAddon) *UserAddonUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAddonUpdate) SetUpdatedAt(v time.Time) *UserAddonUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAddonUpdate) SetUserID(v int64) *UserAddonUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAddonUpdate) SetNillableUserID(v *int64) *UserAddonUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAddonUpdate) AddUserID(v int64) *UserAddonUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *UserAddonUpdate) SetKind(v string) *UserAddonUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *UserAddonUpdate) SetNillableKind(v *string) *UserAddonUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserAddonUpdate) SetAmount(v int) *UserAddonUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserAddonUpdate) SetNillableAmount(v *int) *UserAddonUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserAddonUpdate) AddAmount(v int) *UserAddonUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserAddonUpdate) SetExpiresAt(v time.Time) *UserAddonUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserAddonUpdate) SetNillableExpiresAt(v *time.Time) *UserAddonUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the UserAddonMutation object of the builder.
func (_u *UserAddonUpdate) Mutation() *UserAddonMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAddonUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAddonUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAddonUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAddonUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAddonUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraddon.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAddonUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := useraddon.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "UserAddon.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := useraddon.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "UserAddon.amount": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAddonUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraddon.Table, useraddon.Columns, sqlgraph.NewFieldSpec(useraddon.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraddon.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useraddon.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useraddon.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(useraddon.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(useraddon.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(useraddon.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(useraddon.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraddon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAddonUpdateOne is the builder for updating a single UserAddon entity.
type UserAddonUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAddonMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAddonUpdateOne) SetUpdatedAt(v time.Time) *UserAddonUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAddonUpdateOne) SetUserID(v int64) *UserAddonUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAddonUpdateOne) SetNillableUserID(v *int64) *UserAddonUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAddonUpdateOne) AddUserID(v int64) *UserAddonUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *UserAddonUpdateOne) SetKind(v string) *UserAddonUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *UserAddonUpdateOne) SetNillableKind(v *string) *UserAddonUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserAddonUpdateOne) SetAmount(v int) *UserAddonUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserAddonUpdateOne) SetNillableAmount(v *int) *UserAddonUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserAddonUpdateOne) AddAmount(v int) *UserAddonUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserAddonUpdateOne) SetExpiresAt(v time.Time) *UserAddonUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserAddonUpdateOne) SetNillableExpiresAt(v *time.Time) *UserAddonUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the UserAddonMutation object of the builder.
func (_u *UserAddonUpdateOne) Mutation() *UserAddonMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAddonUpdate builder.
func (_u *UserAddonUpdateOne) Where(ps ...predicate.UserAddon) *UserAddonUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAddonUpdateOne) Select(field string, fields ...string) *UserAddonUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAddon entity.
func (_u *UserAddonUpdateOne) Save(ctx context.Context) (*UserAddon, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAddonUpdateOne) SaveX(ctx context.Context) *UserAddon {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAddonUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAddonUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAddonUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraddon.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAddonUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := useraddon.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "UserAddon.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := useraddon.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "UserAddon.amount": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAddonUpdateOne) sqlSave(ctx context.Context) (_node *UserAddon, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraddon.Table, useraddon.Columns, sqlgraph.NewFieldSpec(useraddon.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAddon.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraddon.FieldID)
		for _, f := range fields {
			if !useraddon.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraddon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraddon.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useraddon.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useraddon.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(useraddon.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(useraddon.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(useraddon.FieldAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(useraddon.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &UserAddon{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraddon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
