// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/viptier"
)

// VIPTier is the model entity for the VIPTier schema.
type VIPTier struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Level holds the value of the "level" field.
	Level int `json:"level,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// MinSpendUsd holds the value of the "min_spend_usd" field.
	MinSpendUsd float64 `json:"min_spend_usd,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// Concurrency holds the value of the "concurrency" field.
	Concurrency int `json:"concurrency,omitempty"`
	// RpmLimit holds the value of the "rpm_limit" field.
	RpmLimit int `json:"rpm_limit,omitempty"`
	// UnlimitedRpm holds the value of the "unlimited_rpm" field.
	UnlimitedRpm bool `json:"unlimited_rpm,omitempty"`
	// UnlimitedConcurrency holds the value of the "unlimited_concurrency" field.
	UnlimitedConcurrency bool `json:"unlimited_concurrency,omitempty"`
	// GraceDays holds the value of the "grace_days" field.
	GraceDays int `json:"grace_days,omitempty"`
	// BadgeColor holds the value of the "badge_color" field.
	BadgeColor string `json:"badge_color,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VIPTier) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case viptier.FieldUnlimitedRpm, viptier.FieldUnlimitedConcurrency, viptier.FieldEnabled:
			values[i] = new(sql.NullBool)
		case viptier.FieldMinSpendUsd, viptier.FieldRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case viptier.FieldID, viptier.FieldLevel, viptier.FieldConcurrency, viptier.FieldRpmLimit, viptier.FieldGraceDays:
			values[i] = new(sql.NullInt64)
		case viptier.FieldName, viptier.FieldBadgeColor:
			values[i] = new(sql.NullString)
		case viptier.FieldCreatedAt, viptier.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VIPTier fields.
func (_m *VIPTier) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case viptier.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case viptier.FieldLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = int(value.Int64)
			}
		case viptier.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case viptier.FieldMinSpendUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field min_spend_usd", values[i])
			} else if value.Valid {
				_m.MinSpendUsd = value.Float64
			}
		case viptier.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case viptier.FieldConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency", values[i])
			} else if value.Valid {
				_m.Concurrency = int(value.Int64)
			}
		case viptier.FieldRpmLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rpm_limit", values[i])
			} else if value.Valid {
				_m.RpmLimit = int(value.Int64)
			}
		case viptier.FieldUnlimitedRpm:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field unlimited_rpm", values[i])
			} else if value.Valid {
				_m.UnlimitedRpm = value.Bool
			}
		case viptier.FieldUnlimitedConcurrency:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field unlimited_concurrency", values[i])
			} else if value.Valid {
				_m.UnlimitedConcurrency = value.Bool
			}
		case viptier.FieldGraceDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grace_days", values[i])
			} else if value.Valid {
				_m.GraceDays = int(value.Int64)
			}
		case viptier.FieldBadgeColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field badge_color", values[i])
			} else if value.Valid {
				_m.BadgeColor = value.String
			}
		case viptier.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case viptier.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case viptier.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VIPTier.
// This includes values selected through modifiers, order, etc.
func (_m *VIPTier) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VIPTier.
// Note that you need to call VIPTier.Unwrap() before calling this method if this VIPTier
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VIPTier) Update() *VIPTierUpdateOne {
	return NewVIPTierClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VIPTier entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VIPTier) Unwrap() *VIPTier {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VIPTier is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VIPTier) String() string {
	var builder strings.Builder
	builder.WriteString("VIPTier(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("min_spend_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinSpendUsd))
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concurrency))
	builder.WriteString(", ")
	builder.WriteString("rpm_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.RpmLimit))
	builder.WriteString(", ")
	builder.WriteString("unlimited_rpm=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnlimitedRpm))
	builder.WriteString(", ")
	builder.WriteString("unlimited_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnlimitedConcurrency))
	builder.WriteString(", ")
	builder.WriteString("grace_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.GraceDays))
	builder.WriteString(", ")
	builder.WriteString("badge_color=")
	builder.WriteString(_m.BadgeColor)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VIPTiers is a parsable slice of VIPTier.
type VIPTiers []*VIPTier
