// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/viptier"
)

// VIPTierUpdate is the builder for updating VIPTier entities.
type VIPTierUpdate struct {
	config
	hooks    []Hook
	mutation *VIPTierMutation
}

// Where appends a list predicates to the VIPTierUpdate builder.
func (_u *VIPTierUpdate) Where(ps ...predicate.VIPTier) *VIPTierUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLevel sets the "level" field.
func (_u *VIPTierUpdate) SetLevel(v int) *VIPTierUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableLevel(v *int) *VIPTierUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *VIPTierUpdate) AddLevel(v int) *VIPTierUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetName sets the "name" field.
func (_u *VIPTierUpdate) SetName(v string) *VIPTierUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableName(v *string) *VIPTierUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMinSpendUsd sets the "min_spend_usd" field.
func (_u *VIPTierUpdate) SetMinSpendUsd(v float64) *VIPTierUpdate {
	_u.mutation.ResetMinSpendUsd()
	_u.mutation.SetMinSpendUsd(v)
	return _u
}

// SetNillableMinSpendUsd sets the "min_spend_usd" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableMinSpendUsd(v *float64) *VIPTierUpdate {
	if v != nil {
		_u.SetMinSpendUsd(*v)
	}
	return _u
}

// AddMinSpendUsd adds value to the "min_spend_usd" field.
func (_u *VIPTierUpdate) AddMinSpendUsd(v float64) *VIPTierUpdate {
	_u.mutation.AddMinSpendUsd(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *VIPTierUpdate) SetRateMultiplier(v float64) *VIPTierUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableRateMultiplier(v *float64) *VIPTierUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *VIPTierUpdate) AddRateMultiplier(v float64) *VIPTierUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *VIPTierUpdate) SetConcurrency(v int) *VIPTierUpdate {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableConcurrency(v *int) *VIPTierUpdate {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *VIPTierUpdate) AddConcurrency(v int) *VIPTierUpdate {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *VIPTierUpdate) SetRpmLimit(v int) *VIPTierUpdate {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableRpmLimit(v *int) *VIPTierUpdate {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *VIPTierUpdate) AddRpmLimit(v int) *VIPTierUpdate {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetUnlimitedRpm sets the "unlimited_rpm" field.
func (_u *VIPTierUpdate) SetUnlimitedRpm(v bool) *VIPTierUpdate {
	_u.mutation.SetUnlimitedRpm(v)
	return _u
}

// SetNillableUnlimitedRpm sets the "unlimited_rpm" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableUnlimitedRpm(v *bool) *VIPTierUpdate {
	if v != nil {
		_u.SetUnlimitedRpm(*v)
	}
	return _u
}

// SetUnlimitedConcurrency sets the "unlimited_concurrency" field.
func (_u *VIPTierUpdate) SetUnlimitedConcurrency(v bool) *VIPTierUpdate {
	_u.mutation.SetUnlimitedConcurrency(v)
	return _u
}

// SetNillableUnlimitedConcurrency sets the "unlimited_concurrency" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableUnlimitedConcurrency(v *bool) *VIPTierUpdate {
	if v != nil {
		_u.SetUnlimitedConcurrency(*v)
	}
	return _u
}

// SetGraceDays sets the "grace_days" field.
func (_u *VIPTierUpdate) SetGraceDays(v int) *VIPTierUpdate {
	_u.mutation.ResetGraceDays()
	_u.mutation.SetGraceDays(v)
	return _u
}

// SetNillableGraceDays sets the "grace_days" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableGraceDays(v *int) *VIPTierUpdate {
	if v != nil {
		_u.SetGraceDays(*v)
	}
	return _u
}

// AddGraceDays adds value to the "grace_days" field.
func (_u *VIPTierUpdate) AddGraceDays(v int) *VIPTierUpdate {
	_u.mutation.AddGraceDays(v)
	return _u
}

// SetBadgeColor sets the "badge_color" field.
func (_u *VIPTierUpdate) SetBadgeColor(v string) *VIPTierUpdate {
	_u.mutation.SetBadgeColor(v)
	return _u
}

// SetNillableBadgeColor sets the "badge_color" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableBadgeColor(v *string) *VIPTierUpdate {
	if v != nil {
		_u.SetBadgeColor(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *VIPTierUpdate) SetEnabled(v bool) *VIPTierUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *VIPTierUpdate) SetNillableEnabled(v *bool) *VIPTierUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VIPTierUpdate) SetUpdatedAt(v time.Time) *VIPTierUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VIPTierMutation object of the builder.
func (_u *VIPTierUpdate) Mutation() *VIPTierMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VIPTierUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VIPTierUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VIPTierUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VIPTierUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VIPTierUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := viptier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VIPTierUpdate) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := viptier.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "VIPTier.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := viptier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VIPTier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Concurrency(); ok {
		if err := viptier.ConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "concurrency", err: fmt.Errorf(`ent: validator failed for field "VIPTier.concurrency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RpmLimit(); ok {
		if err := viptier.RpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "rpm_limit", err: fmt.Errorf(`ent: validator failed for field "VIPTier.rpm_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GraceDays(); ok {
		if err := viptier.GraceDaysValidator(v); err != nil {
			return &ValidationError{Name: "grace_days", err: fmt.Errorf(`ent: validator failed for field "VIPTier.grace_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BadgeColor(); ok {
		if err := viptier.BadgeColorValidator(v); err != nil {
			return &ValidationError{Name: "badge_color", err: fmt.Errorf(`ent: validator failed for field "VIPTier.badge_color": %w`, err)}
		}
	}
	return nil
}

func (_u *VIPTierUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(viptier.Table, viptier.Columns, sqlgraph.NewFieldSpec(viptier.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(viptier.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(viptier.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(viptier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinSpendUsd(); ok {
		_spec.SetField(viptier.FieldMinSpendUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinSpendUsd(); ok {
		_spec.AddField(viptier.FieldMinSpendUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(viptier.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(viptier.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(viptier.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(viptier.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(viptier.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(viptier.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UnlimitedRpm(); ok {
		_spec.SetField(viptier.FieldUnlimitedRpm, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UnlimitedConcurrency(); ok {
		_spec.SetField(viptier.FieldUnlimitedConcurrency, field.TypeBool, value)
	}
	if value, ok := _u.mutation.GraceDays(); ok {
		_spec.SetField(viptier.FieldGraceDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGraceDays(); ok {
		_spec.AddField(viptier.FieldGraceDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BadgeColor(); ok {
		_spec.SetField(viptier.FieldBadgeColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(viptier.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(viptier.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{viptier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VIPTierUpdateOne is the builder for updating a single VIPTier entity.
type VIPTierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VIPTierMutation
}

// SetLevel sets the "level" field.
func (_u *VIPTierUpdateOne) SetLevel(v int) *VIPTierUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableLevel(v *int) *VIPTierUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *VIPTierUpdateOne) AddLevel(v int) *VIPTierUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetName sets the "name" field.
func (_u *VIPTierUpdateOne) SetName(v string) *VIPTierUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableName(v *string) *VIPTierUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMinSpendUsd sets the "min_spend_usd" field.
func (_u *VIPTierUpdateOne) SetMinSpendUsd(v float64) *VIPTierUpdateOne {
	_u.mutation.ResetMinSpendUsd()
	_u.mutation.SetMinSpendUsd(v)
	return _u
}

// SetNillableMinSpendUsd sets the "min_spend_usd" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableMinSpendUsd(v *float64) *VIPTierUpdateOne {
	if v != nil {
		_u.SetMinSpendUsd(*v)
	}
	return _u
}

// AddMinSpendUsd adds value to the "min_spend_usd" field.
func (_u *VIPTierUpdateOne) AddMinSpendUsd(v float64) *VIPTierUpdateOne {
	_u.mutation.AddMinSpendUsd(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *VIPTierUpdateOne) SetRateMultiplier(v float64) *VIPTierUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableRateMultiplier(v *float64) *VIPTierUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *VIPTierUpdateOne) AddRateMultiplier(v float64) *VIPTierUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *VIPTierUpdateOne) SetConcurrency(v int) *VIPTierUpdateOne {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableConcurrency(v *int) *VIPTierUpdateOne {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *VIPTierUpdateOne) AddConcurrency(v int) *VIPTierUpdateOne {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetRpmLimit sets the "rpm_limit" field.
func (_u *VIPTierUpdateOne) SetRpmLimit(v int) *VIPTierUpdateOne {
	_u.mutation.ResetRpmLimit()
	_u.mutation.SetRpmLimit(v)
	return _u
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableRpmLimit(v *int) *VIPTierUpdateOne {
	if v != nil {
		_u.SetRpmLimit(*v)
	}
	return _u
}

// AddRpmLimit adds value to the "rpm_limit" field.
func (_u *VIPTierUpdateOne) AddRpmLimit(v int) *VIPTierUpdateOne {
	_u.mutation.AddRpmLimit(v)
	return _u
}

// SetUnlimitedRpm sets the "unlimited_rpm" field.
func (_u *VIPTierUpdateOne) SetUnlimitedRpm(v bool) *VIPTierUpdateOne {
	_u.mutation.SetUnlimitedRpm(v)
	return _u
}

// SetNillableUnlimitedRpm sets the "unlimited_rpm" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableUnlimitedRpm(v *bool) *VIPTierUpdateOne {
	if v != nil {
		_u.SetUnlimitedRpm(*v)
	}
	return _u
}

// SetUnlimitedConcurrency sets the "unlimited_concurrency" field.
func (_u *VIPTierUpdateOne) SetUnlimitedConcurrency(v bool) *VIPTierUpdateOne {
	_u.mutation.SetUnlimitedConcurrency(v)
	return _u
}

// SetNillableUnlimitedConcurrency sets the "unlimited_concurrency" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableUnlimitedConcurrency(v *bool) *VIPTierUpdateOne {
	if v != nil {
		_u.SetUnlimitedConcurrency(*v)
	}
	return _u
}

// SetGraceDays sets the "grace_days" field.
func (_u *VIPTierUpdateOne) SetGraceDays(v int) *VIPTierUpdateOne {
	_u.mutation.ResetGraceDays()
	_u.mutation.SetGraceDays(v)
	return _u
}

// SetNillableGraceDays sets the "grace_days" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableGraceDays(v *int) *VIPTierUpdateOne {
	if v != nil {
		_u.SetGraceDays(*v)
	}
	return _u
}

// AddGraceDays adds value to the "grace_days" field.
func (_u *VIPTierUpdateOne) AddGraceDays(v int) *VIPTierUpdateOne {
	_u.mutation.AddGraceDays(v)
	return _u
}

// SetBadgeColor sets the "badge_color" field.
func (_u *VIPTierUpdateOne) SetBadgeColor(v string) *VIPTierUpdateOne {
	_u.mutation.SetBadgeColor(v)
	return _u
}

// SetNillableBadgeColor sets the "badge_color" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableBadgeColor(v *string) *VIPTierUpdateOne {
	if v != nil {
		_u.SetBadgeColor(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *VIPTierUpdateOne) SetEnabled(v bool) *VIPTierUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *VIPTierUpdateOne) SetNillableEnabled(v *bool) *VIPTierUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VIPTierUpdateOne) SetUpdatedAt(v time.Time) *VIPTierUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VIPTierMutation object of the builder.
func (_u *VIPTierUpdateOne) Mutation() *VIPTierMutation {
	return _u.mutation
}

// Where appends a list predicates to the VIPTierUpdate builder.
func (_u *VIPTierUpdateOne) Where(ps ...predicate.VIPTier) *VIPTierUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VIPTierUpdateOne) Select(field string, fields ...string) *VIPTierUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VIPTier entity.
func (_u *VIPTierUpdateOne) Save(ctx context.Context) (*VIPTier, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VIPTierUpdateOne) SaveX(ctx context.Context) *VIPTier {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VIPTierUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VIPTierUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VIPTierUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := viptier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VIPTierUpdateOne) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := viptier.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "VIPTier.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := viptier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VIPTier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Concurrency(); ok {
		if err := viptier.ConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "concurrency", err: fmt.Errorf(`ent: validator failed for field "VIPTier.concurrency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RpmLimit(); ok {
		if err := viptier.RpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "rpm_limit", err: fmt.Errorf(`ent: validator failed for field "VIPTier.rpm_limit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GraceDays(); ok {
		if err := viptier.GraceDaysValidator(v); err != nil {
			return &ValidationError{Name: "grace_days", err: fmt.Errorf(`ent: validator failed for field "VIPTier.grace_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BadgeColor(); ok {
		if err := viptier.BadgeColorValidator(v); err != nil {
			return &ValidationError{Name: "badge_color", err: fmt.Errorf(`ent: validator failed for field "VIPTier.badge_color": %w`, err)}
		}
	}
	return nil
}

func (_u *VIPTierUpdateOne) sqlSave(ctx context.Context) (_node *VIPTier, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(viptier.Table, viptier.Columns, sqlgraph.NewFieldSpec(viptier.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VIPTier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, viptier.FieldID)
		for _, f := range fields {
			if !viptier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != viptier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(viptier.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(viptier.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(viptier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinSpendUsd(); ok {
		_spec.SetField(viptier.FieldMinSpendUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinSpendUsd(); ok {
		_spec.AddField(viptier.FieldMinSpendUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(viptier.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(viptier.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(viptier.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(viptier.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmLimit(); ok {
		_spec.SetField(viptier.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmLimit(); ok {
		_spec.AddField(viptier.FieldRpmLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UnlimitedRpm(); ok {
		_spec.SetField(viptier.FieldUnlimitedRpm, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UnlimitedConcurrency(); ok {
		_spec.SetField(viptier.FieldUnlimitedConcurrency, field.TypeBool, value)
	}
	if value, ok := _u.mutation.GraceDays(); ok {
		_spec.SetField(viptier.FieldGraceDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGraceDays(); ok {
		_spec.AddField(viptier.FieldGraceDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BadgeColor(); ok {
		_spec.SetField(viptier.FieldBadgeColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(viptier.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(viptier.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &VIPTier{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{viptier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
