// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/viptier"
)

// VIPTierCreate is the builder for creating a VIPTier entity.
type VIPTierCreate struct {
	config
	mutation *VIPTierMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLevel sets the "level" field.
func (_c *VIPTierCreate) SetLevel(v int) *VIPTierCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetName sets the "name" field.
func (_c *VIPTierCreate) SetName(v string) *VIPTierCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetMinSpendUsd sets the "min_spend_usd" field.
func (_c *VIPTierCreate) SetMinSpendUsd(v float64) *VIPTierCreate {
	_c.mutation.SetMinSpendUsd(v)
	return _c
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_c *VIPTierCreate) SetRateMultiplier(v float64) *VIPTierCreate {
	_c.mutation.SetRateMultiplier(v)
	return _c
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableRateMultiplier(v *float64) *VIPTierCreate {
	if v != nil {
		_c.SetRateMultiplier(*v)
	}
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *VIPTierCreate) SetConcurrency(v int) *VIPTierCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableConcurrency(v *int) *VIPTierCreate {
	if v != nil {
		_c.SetConcurrency(*v)
	}
	return _c
}

// SetRpmLimit sets the "rpm_limit" field.
func (_c *VIPTierCreate) SetRpmLimit(v int) *VIPTierCreate {
	_c.mutation.SetRpmLimit(v)
	return _c
}

// SetNillableRpmLimit sets the "rpm_limit" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableRpmLimit(v *int) *VIPTierCreate {
	if v != nil {
		_c.SetRpmLimit(*v)
	}
	return _c
}

// SetUnlimitedRpm sets the "unlimited_rpm" field.
func (_c *VIPTierCreate) SetUnlimitedRpm(v bool) *VIPTierCreate {
	_c.mutation.SetUnlimitedRpm(v)
	return _c
}

// SetNillableUnlimitedRpm sets the "unlimited_rpm" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableUnlimitedRpm(v *bool) *VIPTierCreate {
	if v != nil {
		_c.SetUnlimitedRpm(*v)
	}
	return _c
}

// SetUnlimitedConcurrency sets the "unlimited_concurrency" field.
func (_c *VIPTierCreate) SetUnlimitedConcurrency(v bool) *VIPTierCreate {
	_c.mutation.SetUnlimitedConcurrency(v)
	return _c
}

// SetNillableUnlimitedConcurrency sets the "unlimited_concurrency" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableUnlimitedConcurrency(v *bool) *VIPTierCreate {
	if v != nil {
		_c.SetUnlimitedConcurrency(*v)
	}
	return _c
}

// SetGraceDays sets the "grace_days" field.
func (_c *VIPTierCreate) SetGraceDays(v int) *VIPTierCreate {
	_c.mutation.SetGraceDays(v)
	return _c
}

// SetNillableGraceDays sets the "grace_days" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableGraceDays(v *int) *VIPTierCreate {
	if v != nil {
		_c.SetGraceDays(*v)
	}
	return _c
}

// SetBadgeColor sets the "badge_color" field.
func (_c *VIPTierCreate) SetBadgeColor(v string) *VIPTierCreate {
	_c.mutation.SetBadgeColor(v)
	return _c
}

// SetNillableBadgeColor sets the "badge_color" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableBadgeColor(v *string) *VIPTierCreate {
	if v != nil {
		_c.SetBadgeColor(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *VIPTierCreate) SetEnabled(v bool) *VIPTierCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableEnabled(v *bool) *VIPTierCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VIPTierCreate) SetCreatedAt(v time.Time) *VIPTierCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableCreatedAt(v *time.Time) *VIPTierCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VIPTierCreate) SetUpdatedAt(v time.Time) *VIPTierCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VIPTierCreate) SetNillableUpdatedAt(v *time.Time) *VIPTierCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the VIPTierMutation object of the builder.
func (_c *VIPTierCreate) Mutation() *VIPTierMutation {
	return _c.mutation
}

// Save creates the VIPTier in the database.
func (_c *VIPTierCreate) Save(ctx context.Context) (*VIPTier, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VIPTierCreate) SaveX(ctx context.Context) *VIPTier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VIPTierCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VIPTierCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VIPTierCreate) defaults() {
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		v := viptier.DefaultRateMultiplier
		_c.mutation.SetRateMultiplier(v)
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		v := viptier.DefaultConcurrency
		_c.mutation.SetConcurrency(v)
	}
	if _, ok := _c.mutation.RpmLimit(); !ok {
		v := viptier.DefaultRpmLimit
		_c.mutation.SetRpmLimit(v)
	}
	if _, ok := _c.mutation.UnlimitedRpm(); !ok {
		v := viptier.DefaultUnlimitedRpm
		_c.mutation.SetUnlimitedRpm(v)
	}
	if _, ok := _c.mutation.UnlimitedConcurrency(); !ok {
		v := viptier.DefaultUnlimitedConcurrency
		_c.mutation.SetUnlimitedConcurrency(v)
	}
	if _, ok := _c.mutation.GraceDays(); !ok {
		v := viptier.DefaultGraceDays
		_c.mutation.SetGraceDays(v)
	}
	if _, ok := _c.mutation.BadgeColor(); !ok {
		v := viptier.DefaultBadgeColor
		_c.mutation.SetBadgeColor(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := viptier.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := viptier.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := viptier.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VIPTierCreate) check() error {
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "VIPTier.level"`)}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := viptier.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "VIPTier.level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "VIPTier.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := viptier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VIPTier.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MinSpendUsd(); !ok {
		return &ValidationError{Name: "min_spend_usd", err: errors.New(`ent: missing required field "VIPTier.min_spend_usd"`)}
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "VIPTier.rate_multiplier"`)}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "VIPTier.concurrency"`)}
	}
	if v, ok := _c.mutation.Concurrency(); ok {
		if err := viptier.ConcurrencyValidator(v); err != nil {
			return &ValidationError{Name: "concurrency", err: fmt.Errorf(`ent: validator failed for field "VIPTier.concurrency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RpmLimit(); !ok {
		return &ValidationError{Name: "rpm_limit", err: errors.New(`ent: missing required field "VIPTier.rpm_limit"`)}
	}
	if v, ok := _c.mutation.RpmLimit(); ok {
		if err := viptier.RpmLimitValidator(v); err != nil {
			return &ValidationError{Name: "rpm_limit", err: fmt.Errorf(`ent: validator failed for field "VIPTier.rpm_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UnlimitedRpm(); !ok {
		return &ValidationError{Name: "unlimited_rpm", err: errors.New(`ent: missing required field "VIPTier.unlimited_rpm"`)}
	}
	if _, ok := _c.mutation.UnlimitedConcurrency(); !ok {
		return &ValidationError{Name: "unlimited_concurrency", err: errors.New(`ent: missing required field "VIPTier.unlimited_concurrency"`)}
	}
	if _, ok := _c.mutation.GraceDays(); !ok {
		return &ValidationError{Name: "grace_days", err: errors.New(`ent: missing required field "VIPTier.grace_days"`)}
	}
	if v, ok := _c.mutation.GraceDays(); ok {
		if err := viptier.GraceDaysValidator(v); err != nil {
			return &ValidationError{Name: "grace_days", err: fmt.Errorf(`ent: validator failed for field "VIPTier.grace_days": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BadgeColor(); !ok {
		return &ValidationError{Name: "badge_color", err: errors.New(`ent: missing required field "VIPTier.badge_color"`)}
	}
	if v, ok := _c.mutation.BadgeColor(); ok {
		if err := viptier.BadgeColorValidator(v); err != nil {
			return &ValidationError{Name: "badge_color", err: fmt.Errorf(`ent: validator failed for field "VIPTier.badge_color": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "VIPTier.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VIPTier.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VIPTier.updated_at"`)}
	}
	return nil
}

func (_c *VIPTierCreate) sqlSave(ctx context.Context) (*VIPTier, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VIPTierCreate) createSpec() (*VIPTier, *sqlgraph.CreateSpec) {
	var (
		_node = &VIPTier{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(viptier.Table, sqlgraph.NewFieldSpec(viptier.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(viptier.FieldLevel, field.TypeInt, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(viptier.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.MinSpendUsd(); ok {
		_spec.SetField(viptier.FieldMinSpendUsd, field.TypeFloat64, value)
		_node.MinSpendUsd = value
	}
	if value, ok := _c.mutation.RateMultiplier(); ok {
		_spec.SetField(viptier.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(viptier.FieldConcurrency, field.TypeInt, value)
		_node.Concurrency = value
	}
	if value, ok := _c.mutation.RpmLimit(); ok {
		_spec.SetField(viptier.FieldRpmLimit, field.TypeInt, value)
		_node.RpmLimit = value
	}
	if value, ok := _c.mutation.UnlimitedRpm(); ok {
		_spec.SetField(viptier.FieldUnlimitedRpm, field.TypeBool, value)
		_node.UnlimitedRpm = value
	}
	if value, ok := _c.mutation.UnlimitedConcurrency(); ok {
		_spec.SetField(viptier.FieldUnlimitedConcurrency, field.TypeBool, value)
		_node.UnlimitedConcurrency = value
	}
	if value, ok := _c.mutation.GraceDays(); ok {
		_spec.SetField(viptier.FieldGraceDays, field.TypeInt, value)
		_node.GraceDays = value
	}
	if value, ok := _c.mutation.BadgeColor(); ok {
		_spec.SetField(viptier.FieldBadgeColor, field.TypeString, value)
		_node.BadgeColor = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(viptier.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(viptier.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(viptier.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VIPTier.Create().
//		SetLevel(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VIPTierUpsert) {
//			SetLevel(v+v).
//		}).
//		Exec(ctx)
func (_c *VIPTierCreate) OnConflict(opts ...sql.ConflictOption) *VIPTierUpsertOne {
	_c.conflict = opts
	return &VIPTierUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VIPTier.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VIPTierCreate) OnConflictColumns(columns ...string) *VIPTierUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VIPTierUpsertOne{
		create: _c,
	}
}

type (
	// VIPTierUpsertOne is the builder for "upsert"-ing
	//  one VIPTier node.
	VIPTierUpsertOne struct {
		create *VIPTierCreate
	}

	// VIPTierUpsert is the "OnConflict" setter.
	VIPTierUpsert struct {
		*sql.UpdateSet
	}
)

// SetLevel sets the "level" field.
func (u *VIPTierUpsert) SetLevel(v int) *VIPTierUpsert {
	u.Set(viptier.FieldLevel, v)
	return u
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateLevel() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldLevel)
	return u
}

// AddLevel adds v to the "level" field.
func (u *VIPTierUpsert) AddLevel(v int) *VIPTierUpsert {
	u.Add(viptier.FieldLevel, v)
	return u
}

// SetName sets the "name" field.
func (u *VIPTierUpsert) SetName(v string) *VIPTierUpsert {
	u.Set(viptier.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateName() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldName)
	return u
}

// SetMinSpendUsd sets the "min_spend_usd" field.
func (u *VIPTierUpsert) SetMinSpendUsd(v float64) *VIPTierUpsert {
	u.Set(viptier.FieldMinSpendUsd, v)
	return u
}

// UpdateMinSpendUsd sets the "min_spend_usd" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateMinSpendUsd() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldMinSpendUsd)
	return u
}

// AddMinSpendUsd adds v to the "min_spend_usd" field.
func (u *VIPTierUpsert) AddMinSpendUsd(v float64) *VIPTierUpsert {
	u.Add(viptier.FieldMinSpendUsd, v)
	return u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *VIPTierUpsert) SetRateMultiplier(v float64) *VIPTierUpsert {
	u.Set(viptier.FieldRateMultiplier, v)
	return u
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateRateMultiplier() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldRateMultiplier)
	return u
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *VIPTierUpsert) AddRateMultiplier(v float64) *VIPTierUpsert {
	u.Add(viptier.FieldRateMultiplier, v)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *VIPTierUpsert) SetConcurrency(v int) *VIPTierUpsert {
	u.Set(viptier.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateConcurrency() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *VIPTierUpsert) AddConcurrency(v int) *VIPTierUpsert {
	u.Add(viptier.FieldConcurrency, v)
	return u
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *VIPTierUpsert) SetRpmLimit(v int) *VIPTierUpsert {
	u.Set(viptier.FieldRpmLimit, v)
	return u
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateRpmLimit() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldRpmLimit)
	return u
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *VIPTierUpsert) AddRpmLimit(v int) *VIPTierUpsert {
	u.Add(viptier.FieldRpmLimit, v)
	return u
}

// SetUnlimitedRpm sets the "unlimited_rpm" field.
func (u *VIPTierUpsert) SetUnlimitedRpm(v bool) *VIPTierUpsert {
	u.Set(viptier.FieldUnlimitedRpm, v)
	return u
}

// UpdateUnlimitedRpm sets the "unlimited_rpm" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateUnlimitedRpm() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldUnlimitedRpm)
	return u
}

// SetUnlimitedConcurrency sets the "unlimited_concurrency" field.
func (u *VIPTierUpsert) SetUnlimitedConcurrency(v bool) *VIPTierUpsert {
	u.Set(viptier.FieldUnlimitedConcurrency, v)
	return u
}

// UpdateUnlimitedConcurrency sets the "unlimited_concurrency" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateUnlimitedConcurrency() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldUnlimitedConcurrency)
	return u
}

// SetGraceDays sets the "grace_days" field.
func (u *VIPTierUpsert) SetGraceDays(v int) *VIPTierUpsert {
	u.Set(viptier.FieldGraceDays, v)
	return u
}

// UpdateGraceDays sets the "grace_days" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateGraceDays() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldGraceDays)
	return u
}

// AddGraceDays adds v to the "grace_days" field.
func (u *VIPTierUpsert) AddGraceDays(v int) *VIPTierUpsert {
	u.Add(viptier.FieldGraceDays, v)
	return u
}

// SetBadgeColor sets the "badge_color" field.
func (u *VIPTierUpsert) SetBadgeColor(v string) *VIPTierUpsert {
	u.Set(viptier.FieldBadgeColor, v)
	return u
}

// UpdateBadgeColor sets the "badge_color" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateBadgeColor() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldBadgeColor)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *VIPTierUpsert) SetEnabled(v bool) *VIPTierUpsert {
	u.Set(viptier.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateEnabled() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldEnabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VIPTierUpsert) SetUpdatedAt(v time.Time) *VIPTierUpsert {
	u.Set(viptier.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VIPTierUpsert) UpdateUpdatedAt() *VIPTierUpsert {
	u.SetExcluded(viptier.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VIPTier.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VIPTierUpsertOne) UpdateNewValues() *VIPTierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(viptier.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VIPTier.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VIPTierUpsertOne) Ignore() *VIPTierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VIPTierUpsertOne) DoNothing() *VIPTierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VIPTierCreate.OnConflict
// documentation for more info.
func (u *VIPTierUpsertOne) Update(set func(*VIPTierUpsert)) *VIPTierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VIPTierUpsert{UpdateSet: update})
	}))
	return u
}

// SetLevel sets the "level" field.
func (u *VIPTierUpsertOne) SetLevel(v int) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetLevel(v)
	})
}

// AddLevel adds v to the "level" field.
func (u *VIPTierUpsertOne) AddLevel(v int) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateLevel() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateLevel()
	})
}

// SetName sets the "name" field.
func (u *VIPTierUpsertOne) SetName(v string) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateName() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateName()
	})
}

// SetMinSpendUsd sets the "min_spend_usd" field.
func (u *VIPTierUpsertOne) SetMinSpendUsd(v float64) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetMinSpendUsd(v)
	})
}

// AddMinSpendUsd adds v to the "min_spend_usd" field.
func (u *VIPTierUpsertOne) AddMinSpendUsd(v float64) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddMinSpendUsd(v)
	})
}

// UpdateMinSpendUsd sets the "min_spend_usd" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateMinSpendUsd() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateMinSpendUsd()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *VIPTierUpsertOne) SetRateMultiplier(v float64) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *VIPTierUpsertOne) AddRateMultiplier(v float64) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateRateMultiplier() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *VIPTierUpsertOne) SetConcurrency(v int) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *VIPTierUpsertOne) AddConcurrency(v int) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateConcurrency() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateConcurrency()
	})
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *VIPTierUpsertOne) SetRpmLimit(v int) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetRpmLimit(v)
	})
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *VIPTierUpsertOne) AddRpmLimit(v int) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddRpmLimit(v)
	})
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateRpmLimit() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateRpmLimit()
	})
}

// SetUnlimitedRpm sets the "unlimited_rpm" field.
func (u *VIPTierUpsertOne) SetUnlimitedRpm(v bool) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetUnlimitedRpm(v)
	})
}

// UpdateUnlimitedRpm sets the "unlimited_rpm" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateUnlimitedRpm() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateUnlimitedRpm()
	})
}

// SetUnlimitedConcurrency sets the "unlimited_concurrency" field.
func (u *VIPTierUpsertOne) SetUnlimitedConcurrency(v bool) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetUnlimitedConcurrency(v)
	})
}

// UpdateUnlimitedConcurrency sets the "unlimited_concurrency" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateUnlimitedConcurrency() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateUnlimitedConcurrency()
	})
}

// SetGraceDays sets the "grace_days" field.
func (u *VIPTierUpsertOne) SetGraceDays(v int) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetGraceDays(v)
	})
}

// AddGraceDays adds v to the "grace_days" field.
func (u *VIPTierUpsertOne) AddGraceDays(v int) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddGraceDays(v)
	})
}

// UpdateGraceDays sets the "grace_days" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateGraceDays() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateGraceDays()
	})
}

// SetBadgeColor sets the "badge_color" field.
func (u *VIPTierUpsertOne) SetBadgeColor(v string) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetBadgeColor(v)
	})
}

// UpdateBadgeColor sets the "badge_color" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateBadgeColor() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateBadgeColor()
	})
}

// SetEnabled sets the "enabled" field.
func (u *VIPTierUpsertOne) SetEnabled(v bool) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateEnabled() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VIPTierUpsertOne) SetUpdatedAt(v time.Time) *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VIPTierUpsertOne) UpdateUpdatedAt() *VIPTierUpsertOne {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VIPTierUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VIPTierCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VIPTierUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VIPTierUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VIPTierUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VIPTierCreateBulk is the builder for creating many VIPTier entities in bulk.
type VIPTierCreateBulk struct {
	config
	err      error
	builders []*VIPTierCreate
	conflict []sql.ConflictOption
}

// Save creates the VIPTier entities in the database.
func (_c *VIPTierCreateBulk) Save(ctx context.Context) ([]*VIPTier, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VIPTier, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VIPTierMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VIPTierCreateBulk) SaveX(ctx context.Context) []*VIPTier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VIPTierCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VIPTierCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VIPTier.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VIPTierUpsert) {
//			SetLevel(v+v).
//		}).
//		Exec(ctx)
func (_c *VIPTierCreateBulk) OnConflict(opts ...sql.ConflictOption) *VIPTierUpsertBulk {
	_c.conflict = opts
	return &VIPTierUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VIPTier.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VIPTierCreateBulk) OnConflictColumns(columns ...string) *VIPTierUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VIPTierUpsertBulk{
		create: _c,
	}
}

// VIPTierUpsertBulk is the builder for "upsert"-ing
// a bulk of VIPTier nodes.
type VIPTierUpsertBulk struct {
	create *VIPTierCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VIPTier.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VIPTierUpsertBulk) UpdateNewValues() *VIPTierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(viptier.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VIPTier.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VIPTierUpsertBulk) Ignore() *VIPTierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VIPTierUpsertBulk) DoNothing() *VIPTierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VIPTierCreateBulk.OnConflict
// documentation for more info.
func (u *VIPTierUpsertBulk) Update(set func(*VIPTierUpsert)) *VIPTierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VIPTierUpsert{UpdateSet: update})
	}))
	return u
}

// SetLevel sets the "level" field.
func (u *VIPTierUpsertBulk) SetLevel(v int) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetLevel(v)
	})
}

// AddLevel adds v to the "level" field.
func (u *VIPTierUpsertBulk) AddLevel(v int) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddLevel(v)
	})
}

// UpdateLevel sets the "level" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateLevel() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateLevel()
	})
}

// SetName sets the "name" field.
func (u *VIPTierUpsertBulk) SetName(v string) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateName() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateName()
	})
}

// SetMinSpendUsd sets the "min_spend_usd" field.
func (u *VIPTierUpsertBulk) SetMinSpendUsd(v float64) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetMinSpendUsd(v)
	})
}

// AddMinSpendUsd adds v to the "min_spend_usd" field.
func (u *VIPTierUpsertBulk) AddMinSpendUsd(v float64) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddMinSpendUsd(v)
	})
}

// UpdateMinSpendUsd sets the "min_spend_usd" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateMinSpendUsd() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateMinSpendUsd()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *VIPTierUpsertBulk) SetRateMultiplier(v float64) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *VIPTierUpsertBulk) AddRateMultiplier(v float64) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateRateMultiplier() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *VIPTierUpsertBulk) SetConcurrency(v int) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *VIPTierUpsertBulk) AddConcurrency(v int) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateConcurrency() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateConcurrency()
	})
}

// SetRpmLimit sets the "rpm_limit" field.
func (u *VIPTierUpsertBulk) SetRpmLimit(v int) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetRpmLimit(v)
	})
}

// AddRpmLimit adds v to the "rpm_limit" field.
func (u *VIPTierUpsertBulk) AddRpmLimit(v int) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddRpmLimit(v)
	})
}

// UpdateRpmLimit sets the "rpm_limit" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateRpmLimit() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateRpmLimit()
	})
}

// SetUnlimitedRpm sets the "unlimited_rpm" field.
func (u *VIPTierUpsertBulk) SetUnlimitedRpm(v bool) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetUnlimitedRpm(v)
	})
}

// UpdateUnlimitedRpm sets the "unlimited_rpm" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateUnlimitedRpm() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateUnlimitedRpm()
	})
}

// SetUnlimitedConcurrency sets the "unlimited_concurrency" field.
func (u *VIPTierUpsertBulk) SetUnlimitedConcurrency(v bool) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetUnlimitedConcurrency(v)
	})
}

// UpdateUnlimitedConcurrency sets the "unlimited_concurrency" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateUnlimitedConcurrency() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateUnlimitedConcurrency()
	})
}

// SetGraceDays sets the "grace_days" field.
func (u *VIPTierUpsertBulk) SetGraceDays(v int) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetGraceDays(v)
	})
}

// AddGraceDays adds v to the "grace_days" field.
func (u *VIPTierUpsertBulk) AddGraceDays(v int) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.AddGraceDays(v)
	})
}

// UpdateGraceDays sets the "grace_days" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateGraceDays() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateGraceDays()
	})
}

// SetBadgeColor sets the "badge_color" field.
func (u *VIPTierUpsertBulk) SetBadgeColor(v string) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetBadgeColor(v)
	})
}

// UpdateBadgeColor sets the "badge_color" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateBadgeColor() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateBadgeColor()
	})
}

// SetEnabled sets the "enabled" field.
func (u *VIPTierUpsertBulk) SetEnabled(v bool) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateEnabled() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VIPTierUpsertBulk) SetUpdatedAt(v time.Time) *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VIPTierUpsertBulk) UpdateUpdatedAt() *VIPTierUpsertBulk {
	return u.Update(func(s *VIPTierUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VIPTierUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VIPTierCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VIPTierCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VIPTierUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
